import { readFile, writeFile } from "node:fs/promises";
import { UI_TRANSLATION_ENTRIES } from "../src/localization.mjs";

const base = {
  ...JSON.parse(await readFile("lang/en.json", "utf8")),
  ...UI_TRANSLATION_ENTRIES,
};
const common = {
  "SWFFG.System.Title": "Star Wars FFG",
  "SWFFG.System.About": "About Star Wars FFG",
  "SWFFG.Common.Close": "Close",
  "SWFFG.Common.Cancel": "Cancel",
  "SWFFG.Common.Save": "Save",
  "SWFFG.Common.Search": "Search",
  "SWFFG.Common.Open": "Open",
  "SWFFG.Common.Record": "Record",
  "SWFFG.Common.Apply": "Apply",
  "SWFFG.Common.Back": "Back",
  "SWFFG.Common.Next": "Next",
};
const groups = {
  "SWFFG.Settings.Groups.CampaignSetup": "Campaign setup",
  "SWFFG.Settings.Groups.Appearance": "Appearance",
  "SWFFG.Settings.Groups.CombatTurns": "Combat & turns",
  "SWFFG.Settings.Groups.PlayTools": "Play tools",
  "SWFFG.Settings.Groups.ImportsSources": "Imports & private sources",
  "SWFFG.Settings.Groups.HelpDiagnostics": "Help & diagnostics",
  "SWFFG.Settings.Groups.Other": "Other Star Wars settings",
};
const settings = {
  "SWFFG.Settings.About.Name": "About Star Wars FFG",
  "SWFFG.Settings.About.Label": "About",
  "SWFFG.Settings.About.Hint": "Show the system and Foundry versions loaded in this game session.",
  "SWFFG.Settings.Destiny.Name": "Session Destiny pool",
  "SWFFG.Settings.Destiny.Hint": "Roll and manage the shared Light and Dark Destiny points.",
  "SWFFG.Settings.Reference.Name": "Reference catalogue",
  "SWFFG.Settings.Reference.Label": "Search database",
  "SWFFG.Settings.Reference.Hint": "Find names, statistics, notes and book pages in the bundled database.",
  "SWFFG.Settings.DataReview.Name": "Rule data review",
  "SWFFG.Settings.DataReview.Label": "Review missing data",
  "SWFFG.Settings.DataReview.Hint": "Edit and validate missing source references, paraphrases and declarative talent or equipment rules.",
  "SWFFG.Settings.OwnedBooks.Name": "Owned books",
  "SWFFG.Settings.OwnedBooks.Label": "Choose available books",
  "SWFFG.Settings.OwnedBooks.Hint": "Apply one reference filter for the GM and players.",
  "SWFFG.Settings.Console.Name": "Session console",
  "SWFFG.Settings.Console.Label": "Dice & Destiny",
  "SWFFG.Settings.Console.Hint": "Roll custom dice and manage the shared Destiny pool.",
};
const hud = {
  "SWFFG.HUD.Destiny": "Destiny",
  "SWFFG.HUD.Light": "Light",
  "SWFFG.HUD.Dark": "Dark",
  "SWFFG.HUD.Actions": "Actions",
  "SWFFG.HUD.Maneuvers": "Maneuvers",
  "SWFFG.Sheets.Equipment": "Equipment",
  "SWFFG.Sheets.Abilities": "Abilities",
  "SWFFG.Sheets.Biography": "Biography",
};
const typeLabels = {
  "TYPES.Actor.character": "Character",
  "TYPES.Actor.minion": "Minion group",
  "TYPES.Actor.rival": "Rival",
  "TYPES.Actor.nemesis": "Nemesis",
  "TYPES.Actor.vehicle": "Vehicle",
  "TYPES.Actor.group": "Group",
  "TYPES.Item.weapon": "Weapon",
  "TYPES.Item.armor": "Armor",
  "TYPES.Item.gear": "Gear",
  "TYPES.Item.talent": "Talent",
  "TYPES.Item.forcePower": "Force power",
  "TYPES.Item.species": "Species",
  "TYPES.Item.career": "Career",
  "TYPES.Item.specialization": "Specialization",
  "TYPES.Item.signatureAbility": "Signature ability",
  "TYPES.Item.attachment": "Attachment",
  "TYPES.Item.reference": "Reference",
};
const translated = (types, values) => ({ ...typeLabels, ...common, ...groups, ...settings, ...hud, ...types, ...values });
const locales = {
  "en-GB": { ...common, ...groups, ...settings, ...hud, "TYPES.Item.armor": "Armour", "SWFFG.Settings.Groups.CombatTurns": "Combat & manoeuvres", "SWFFG.HUD.Maneuvers": "Manoeuvres" },
  "en-US": {},
  es: translated({
    "TYPES.Actor.character": "Personaje", "TYPES.Actor.minion": "Grupo de esbirros", "TYPES.Actor.vehicle": "Vehículo", "TYPES.Item.weapon": "Arma", "TYPES.Item.armor": "Armadura", "TYPES.Item.gear": "Equipo", "TYPES.Item.talent": "Talento", "TYPES.Item.forcePower": "Poder de la Fuerza", "TYPES.Item.species": "Especie", "TYPES.Item.career": "Carrera", "TYPES.Item.specialization": "Especialización", "TYPES.Item.signatureAbility": "Habilidad característica", "TYPES.Item.attachment": "Accesorio", "TYPES.Item.reference": "Referencia"
  }, {
    "SWFFG.System.About": "Acerca de Star Wars FFG", "SWFFG.Common.Close": "Cerrar", "SWFFG.Common.Cancel": "Cancelar", "SWFFG.Common.Save": "Guardar", "SWFFG.Common.Search": "Buscar", "SWFFG.Common.Open": "Abrir", "SWFFG.Common.Record": "Registrar", "SWFFG.Common.Apply": "Aplicar", "SWFFG.Common.Back": "Atrás", "SWFFG.Common.Next": "Siguiente", "SWFFG.Settings.Groups.CampaignSetup": "Configuración de campaña", "SWFFG.Settings.Groups.Appearance": "Apariencia", "SWFFG.Settings.Groups.CombatTurns": "Combate y turnos", "SWFFG.Settings.Groups.PlayTools": "Herramientas de juego", "SWFFG.Settings.Groups.ImportsSources": "Importaciones y fuentes privadas", "SWFFG.Settings.Groups.HelpDiagnostics": "Ayuda y diagnóstico", "SWFFG.Settings.Groups.Other": "Otros ajustes de Star Wars", "SWFFG.Settings.About.Name": "Acerca de Star Wars FFG", "SWFFG.Settings.About.Label": "Acerca de", "SWFFG.Settings.Destiny.Name": "Reserva de Destino de la sesión", "SWFFG.Settings.Reference.Label": "Buscar en la base de datos", "SWFFG.Settings.DataReview.Label": "Revisar datos faltantes", "SWFFG.Settings.OwnedBooks.Label": "Elegir libros disponibles", "SWFFG.Settings.Console.Label": "Dados y Destino", "SWFFG.HUD.Destiny": "Destino", "SWFFG.HUD.Light": "Luz", "SWFFG.HUD.Dark": "Oscuridad", "SWFFG.HUD.Actions": "Acciones", "SWFFG.HUD.Maneuvers": "Maniobras", "SWFFG.Sheets.Equipment": "Equipo", "SWFFG.Sheets.Abilities": "Habilidades", "SWFFG.Sheets.Biography": "Biografía"
  }),
  fr: translated({
    "TYPES.Actor.character": "Personnage", "TYPES.Actor.minion": "Groupe de sbires", "TYPES.Actor.vehicle": "Véhicule", "TYPES.Item.weapon": "Arme", "TYPES.Item.armor": "Armure", "TYPES.Item.gear": "Équipement", "TYPES.Item.forcePower": "Pouvoir de la Force", "TYPES.Item.species": "Espèce", "TYPES.Item.career": "Carrière", "TYPES.Item.specialization": "Spécialisation", "TYPES.Item.signatureAbility": "Capacité signature", "TYPES.Item.attachment": "Accessoire"
  }, {
    "SWFFG.System.About": "À propos de Star Wars FFG", "SWFFG.Common.Close": "Fermer", "SWFFG.Common.Cancel": "Annuler", "SWFFG.Common.Save": "Enregistrer", "SWFFG.Common.Search": "Rechercher", "SWFFG.Common.Open": "Ouvrir", "SWFFG.Common.Record": "Consigner", "SWFFG.Common.Apply": "Appliquer", "SWFFG.Common.Back": "Retour", "SWFFG.Common.Next": "Suivant", "SWFFG.Settings.Groups.CampaignSetup": "Configuration de campagne", "SWFFG.Settings.Groups.Appearance": "Apparence", "SWFFG.Settings.Groups.CombatTurns": "Combat et tours", "SWFFG.Settings.Groups.PlayTools": "Outils de jeu", "SWFFG.Settings.Groups.ImportsSources": "Imports et sources privées", "SWFFG.Settings.Groups.HelpDiagnostics": "Aide et diagnostics", "SWFFG.Settings.Groups.Other": "Autres réglages Star Wars", "SWFFG.Settings.About.Name": "À propos de Star Wars FFG", "SWFFG.Settings.About.Label": "À propos", "SWFFG.Settings.Destiny.Name": "Réserve de Destinée de la session", "SWFFG.Settings.Reference.Label": "Rechercher dans la base", "SWFFG.Settings.DataReview.Label": "Réviser les données manquantes", "SWFFG.Settings.OwnedBooks.Label": "Choisir les livres disponibles", "SWFFG.Settings.Console.Label": "Dés et Destinée", "SWFFG.HUD.Destiny": "Destinée", "SWFFG.HUD.Light": "Lumière", "SWFFG.HUD.Dark": "Obscurité", "SWFFG.HUD.Actions": "Actions", "SWFFG.HUD.Maneuvers": "Manœuvres", "SWFFG.Sheets.Equipment": "Équipement", "SWFFG.Sheets.Abilities": "Capacités", "SWFFG.Sheets.Biography": "Biographie"
  }),
  de: translated({
    "TYPES.Actor.character": "Charakter", "TYPES.Actor.minion": "Schergen-Gruppe", "TYPES.Actor.vehicle": "Fahrzeug", "TYPES.Item.weapon": "Waffe", "TYPES.Item.armor": "Rüstung", "TYPES.Item.gear": "Ausrüstung", "TYPES.Item.forcePower": "Machtfähigkeit", "TYPES.Item.species": "Spezies", "TYPES.Item.career": "Karriere", "TYPES.Item.specialization": "Spezialisierung", "TYPES.Item.signatureAbility": "Signaturfähigkeit", "TYPES.Item.attachment": "Anhang"
  }, {
    "SWFFG.System.About": "Über Star Wars FFG", "SWFFG.Common.Close": "Schließen", "SWFFG.Common.Cancel": "Abbrechen", "SWFFG.Common.Save": "Speichern", "SWFFG.Common.Search": "Suchen", "SWFFG.Common.Open": "Öffnen", "SWFFG.Common.Record": "Aufzeichnen", "SWFFG.Common.Apply": "Anwenden", "SWFFG.Common.Back": "Zurück", "SWFFG.Common.Next": "Weiter", "SWFFG.Settings.Groups.CampaignSetup": "Kampagnenaufbau", "SWFFG.Settings.Groups.Appearance": "Darstellung", "SWFFG.Settings.Groups.CombatTurns": "Kampf und Runden", "SWFFG.Settings.Groups.PlayTools": "Spielwerkzeuge", "SWFFG.Settings.Groups.ImportsSources": "Importe und private Quellen", "SWFFG.Settings.Groups.HelpDiagnostics": "Hilfe und Diagnose", "SWFFG.Settings.Groups.Other": "Weitere Star-Wars-Einstellungen", "SWFFG.Settings.About.Name": "Über Star Wars FFG", "SWFFG.Settings.About.Label": "Über", "SWFFG.Settings.Destiny.Name": "Destiny-Pool der Sitzung", "SWFFG.Settings.Reference.Label": "Datenbank durchsuchen", "SWFFG.Settings.DataReview.Label": "Fehlende Daten prüfen", "SWFFG.Settings.OwnedBooks.Label": "Verfügbare Bücher wählen", "SWFFG.Settings.Console.Label": "Würfel und Destiny", "SWFFG.HUD.Destiny": "Destiny", "SWFFG.HUD.Light": "Licht", "SWFFG.HUD.Dark": "Dunkelheit", "SWFFG.HUD.Actions": "Aktionen", "SWFFG.HUD.Maneuvers": "Manöver", "SWFFG.Sheets.Equipment": "Ausrüstung", "SWFFG.Sheets.Abilities": "Fähigkeiten", "SWFFG.Sheets.Biography": "Biografie"
  }),
  it: {},
  "pt-BR": {}, "pt-PT": {}, ja: {}, ko: {}, "zh-CN": {}, "zh-TW": {}, pl: {}, ru: {}, nl: {}, sv: {}
};

const setLocale = (locale, values) => { locales[locale] = { ...locales[locale], ...values }; };
setLocale("it", {
  "TYPES.Actor.character": "Personaggio", "TYPES.Actor.minion": "Gruppo di minion", "TYPES.Actor.rival": "Rivale", "TYPES.Actor.nemesis": "Nemesi", "TYPES.Actor.vehicle": "Veicolo", "TYPES.Actor.group": "Gruppo", "TYPES.Item.weapon": "Arma", "TYPES.Item.armor": "Armatura", "TYPES.Item.gear": "Equipaggiamento", "TYPES.Item.talent": "Talento", "TYPES.Item.forcePower": "Potere della Forza", "TYPES.Item.species": "Specie", "TYPES.Item.career": "Carriera", "TYPES.Item.specialization": "Specializzazione", "TYPES.Item.signatureAbility": "Abilità distintiva", "TYPES.Item.attachment": "Accessorio", "TYPES.Item.reference": "Riferimento",
  "SWFFG.System.About": "Informazioni su Star Wars FFG", "SWFFG.Common.Close": "Chiudi", "SWFFG.Common.Cancel": "Annulla", "SWFFG.Common.Save": "Salva", "SWFFG.Common.Search": "Cerca", "SWFFG.Common.Open": "Apri", "SWFFG.Common.Record": "Registra", "SWFFG.Common.Apply": "Applica", "SWFFG.Common.Back": "Indietro", "SWFFG.Common.Next": "Avanti", "SWFFG.Settings.Groups.CampaignSetup": "Impostazioni campagna", "SWFFG.Settings.Groups.Appearance": "Aspetto", "SWFFG.Settings.Groups.CombatTurns": "Combattimento e turni", "SWFFG.Settings.Groups.PlayTools": "Strumenti di gioco", "SWFFG.Settings.Groups.ImportsSources": "Importazioni e fonti private", "SWFFG.Settings.Groups.HelpDiagnostics": "Aiuto e diagnostica", "SWFFG.Settings.Groups.Other": "Altre impostazioni Star Wars", "SWFFG.HUD.Destiny": "Destino", "SWFFG.HUD.Light": "Luce", "SWFFG.HUD.Dark": "Oscurità", "SWFFG.HUD.Actions": "Azioni", "SWFFG.HUD.Maneuvers": "Manovre", "SWFFG.Sheets.Equipment": "Equipaggiamento", "SWFFG.Sheets.Abilities": "Abilità", "SWFFG.Sheets.Biography": "Biografia"
});
setLocale("pt-BR", {
  "TYPES.Actor.character": "Personagem", "TYPES.Actor.minion": "Grupo de lacaios", "TYPES.Actor.rival": "Rival", "TYPES.Actor.nemesis": "Nêmesis", "TYPES.Actor.vehicle": "Veículo", "TYPES.Actor.group": "Grupo", "TYPES.Item.weapon": "Arma", "TYPES.Item.armor": "Armadura", "TYPES.Item.gear": "Equipamento", "TYPES.Item.talent": "Talento", "TYPES.Item.forcePower": "Poder da Força", "TYPES.Item.species": "Espécie", "TYPES.Item.career": "Carreira", "TYPES.Item.specialization": "Especialização", "TYPES.Item.signatureAbility": "Habilidade característica", "TYPES.Item.attachment": "Acessório", "TYPES.Item.reference": "Referência",
  "SWFFG.System.About": "Sobre Star Wars FFG", "SWFFG.Common.Close": "Fechar", "SWFFG.Common.Cancel": "Cancelar", "SWFFG.Common.Save": "Salvar", "SWFFG.Common.Search": "Pesquisar", "SWFFG.Common.Open": "Abrir", "SWFFG.Common.Record": "Registrar", "SWFFG.Common.Apply": "Aplicar", "SWFFG.Common.Back": "Voltar", "SWFFG.Common.Next": "Avançar", "SWFFG.Settings.Groups.CampaignSetup": "Configuração da campanha", "SWFFG.Settings.Groups.Appearance": "Aparência", "SWFFG.Settings.Groups.CombatTurns": "Combate e turnos", "SWFFG.Settings.Groups.PlayTools": "Ferramentas de jogo", "SWFFG.Settings.Groups.ImportsSources": "Importações e fontes privadas", "SWFFG.Settings.Groups.HelpDiagnostics": "Ajuda e diagnósticos", "SWFFG.Settings.Groups.Other": "Outras configurações de Star Wars", "SWFFG.HUD.Destiny": "Destino", "SWFFG.HUD.Light": "Luz", "SWFFG.HUD.Dark": "Trevas", "SWFFG.HUD.Actions": "Ações", "SWFFG.HUD.Maneuvers": "Manobras", "SWFFG.Sheets.Equipment": "Equipamento", "SWFFG.Sheets.Abilities": "Habilidades", "SWFFG.Sheets.Biography": "Biografia"
});
setLocale("pt-PT", {
  "TYPES.Actor.character": "Personagem", "TYPES.Actor.minion": "Grupo de lacaios", "TYPES.Actor.rival": "Rival", "TYPES.Actor.nemesis": "Némesis", "TYPES.Actor.vehicle": "Veículo", "TYPES.Actor.group": "Grupo", "TYPES.Item.weapon": "Arma", "TYPES.Item.armor": "Armadura", "TYPES.Item.gear": "Equipamento", "TYPES.Item.talent": "Talento", "TYPES.Item.forcePower": "Poder da Força", "TYPES.Item.species": "Espécie", "TYPES.Item.career": "Carreira", "TYPES.Item.specialization": "Especialização", "TYPES.Item.signatureAbility": "Habilidade de assinatura", "TYPES.Item.attachment": "Acessório", "TYPES.Item.reference": "Referência",
  "SWFFG.System.About": "Sobre Star Wars FFG", "SWFFG.Common.Close": "Fechar", "SWFFG.Common.Cancel": "Cancelar", "SWFFG.Common.Save": "Guardar", "SWFFG.Common.Search": "Pesquisar", "SWFFG.Common.Open": "Abrir", "SWFFG.Common.Record": "Registar", "SWFFG.Common.Apply": "Aplicar", "SWFFG.Common.Back": "Voltar", "SWFFG.Common.Next": "Seguinte", "SWFFG.Settings.Groups.CampaignSetup": "Configuração da campanha", "SWFFG.Settings.Groups.Appearance": "Aspeto", "SWFFG.Settings.Groups.CombatTurns": "Combate e turnos", "SWFFG.Settings.Groups.PlayTools": "Ferramentas de jogo", "SWFFG.Settings.Groups.ImportsSources": "Importações e fontes privadas", "SWFFG.Settings.Groups.HelpDiagnostics": "Ajuda e diagnóstico", "SWFFG.Settings.Groups.Other": "Outras definições de Star Wars", "SWFFG.HUD.Destiny": "Destino", "SWFFG.HUD.Light": "Luz", "SWFFG.HUD.Dark": "Trevas", "SWFFG.HUD.Actions": "Ações", "SWFFG.HUD.Maneuvers": "Manobras", "SWFFG.Sheets.Equipment": "Equipamento", "SWFFG.Sheets.Abilities": "Habilidades", "SWFFG.Sheets.Biography": "Biografia"
});
setLocale("ja", {
  "TYPES.Actor.character": "キャラクター", "TYPES.Actor.minion": "ミニオン・グループ", "TYPES.Actor.rival": "ライバル", "TYPES.Actor.nemesis": "ネメシス", "TYPES.Actor.vehicle": "ビークル", "TYPES.Actor.group": "グループ", "TYPES.Item.weapon": "武器", "TYPES.Item.armor": "防具", "TYPES.Item.gear": "ギア", "TYPES.Item.talent": "タレント", "TYPES.Item.forcePower": "フォースの力", "TYPES.Item.species": "種族", "TYPES.Item.career": "キャリア", "TYPES.Item.specialization": "スペシャライゼーション", "TYPES.Item.signatureAbility": "シグネチャー・アビリティ", "TYPES.Item.attachment": "アタッチメント", "TYPES.Item.reference": "リファレンス",
  "SWFFG.System.About": "Star Wars FFGについて", "SWFFG.Common.Close": "閉じる", "SWFFG.Common.Cancel": "キャンセル", "SWFFG.Common.Save": "保存", "SWFFG.Common.Search": "検索", "SWFFG.Common.Open": "開く", "SWFFG.Common.Record": "記録", "SWFFG.Common.Apply": "適用", "SWFFG.Common.Back": "戻る", "SWFFG.Common.Next": "次へ", "SWFFG.Settings.Groups.CampaignSetup": "キャンペーン設定", "SWFFG.Settings.Groups.Appearance": "外観", "SWFFG.Settings.Groups.CombatTurns": "戦闘とターン", "SWFFG.Settings.Groups.PlayTools": "プレイツール", "SWFFG.Settings.Groups.ImportsSources": "インポートと非公開ソース", "SWFFG.Settings.Groups.HelpDiagnostics": "ヘルプと診断", "SWFFG.Settings.Groups.Other": "その他のStar Wars設定", "SWFFG.HUD.Destiny": "Destiny", "SWFFG.HUD.Light": "Light", "SWFFG.HUD.Dark": "Dark", "SWFFG.HUD.Actions": "アクション", "SWFFG.HUD.Maneuvers": "マヌーバー", "SWFFG.Sheets.Equipment": "装備", "SWFFG.Sheets.Abilities": "アビリティ", "SWFFG.Sheets.Biography": "人物紹介"
});
setLocale("ko", {
  "TYPES.Actor.character": "캐릭터", "TYPES.Actor.minion": "미니언 그룹", "TYPES.Actor.rival": "라이벌", "TYPES.Actor.nemesis": "네메시스", "TYPES.Actor.vehicle": "탈것", "TYPES.Actor.group": "그룹", "TYPES.Item.weapon": "무기", "TYPES.Item.armor": "방어구", "TYPES.Item.gear": "장비", "TYPES.Item.talent": "재능", "TYPES.Item.forcePower": "포스 능력", "TYPES.Item.species": "종족", "TYPES.Item.career": "커리어", "TYPES.Item.specialization": "전문화", "TYPES.Item.signatureAbility": "시그니처 능력", "TYPES.Item.attachment": "부착물", "TYPES.Item.reference": "참조",
  "SWFFG.System.About": "Star Wars FFG 정보", "SWFFG.Common.Close": "닫기", "SWFFG.Common.Cancel": "취소", "SWFFG.Common.Save": "저장", "SWFFG.Common.Search": "검색", "SWFFG.Common.Open": "열기", "SWFFG.Common.Record": "기록", "SWFFG.Common.Apply": "적용", "SWFFG.Common.Back": "뒤로", "SWFFG.Common.Next": "다음", "SWFFG.Settings.Groups.CampaignSetup": "캠페인 설정", "SWFFG.Settings.Groups.Appearance": "화면", "SWFFG.Settings.Groups.CombatTurns": "전투 및 턴", "SWFFG.Settings.Groups.PlayTools": "플레이 도구", "SWFFG.Settings.Groups.ImportsSources": "가져오기 및 비공개 출처", "SWFFG.Settings.Groups.HelpDiagnostics": "도움말 및 진단", "SWFFG.Settings.Groups.Other": "기타 Star Wars 설정", "SWFFG.HUD.Destiny": "Destiny", "SWFFG.HUD.Light": "빛", "SWFFG.HUD.Dark": "어둠", "SWFFG.HUD.Actions": "행동", "SWFFG.HUD.Maneuvers": "기동", "SWFFG.Sheets.Equipment": "장비", "SWFFG.Sheets.Abilities": "능력", "SWFFG.Sheets.Biography": "배경"
});
setLocale("zh-CN", {
  "TYPES.Actor.character": "角色", "TYPES.Actor.minion": "杂兵组", "TYPES.Actor.rival": "对手", "TYPES.Actor.nemesis": "宿敌", "TYPES.Actor.vehicle": "载具", "TYPES.Actor.group": "小组", "TYPES.Item.weapon": "武器", "TYPES.Item.armor": "护甲", "TYPES.Item.gear": "装备", "TYPES.Item.talent": "天赋", "TYPES.Item.forcePower": "原力能力", "TYPES.Item.species": "种族", "TYPES.Item.career": "职业", "TYPES.Item.specialization": "专精", "TYPES.Item.signatureAbility": "标志性能力", "TYPES.Item.attachment": "附件", "TYPES.Item.reference": "参考",
  "SWFFG.System.About": "关于 Star Wars FFG", "SWFFG.Common.Close": "关闭", "SWFFG.Common.Cancel": "取消", "SWFFG.Common.Save": "保存", "SWFFG.Common.Search": "搜索", "SWFFG.Common.Open": "打开", "SWFFG.Common.Record": "记录", "SWFFG.Common.Apply": "应用", "SWFFG.Common.Back": "返回", "SWFFG.Common.Next": "下一步", "SWFFG.Settings.Groups.CampaignSetup": "战役设置", "SWFFG.Settings.Groups.Appearance": "外观", "SWFFG.Settings.Groups.CombatTurns": "战斗与回合", "SWFFG.Settings.Groups.PlayTools": "游戏工具", "SWFFG.Settings.Groups.ImportsSources": "导入与私有来源", "SWFFG.Settings.Groups.HelpDiagnostics": "帮助与诊断", "SWFFG.Settings.Groups.Other": "其他 Star Wars 设置", "SWFFG.HUD.Destiny": "命运", "SWFFG.HUD.Light": "光明", "SWFFG.HUD.Dark": "黑暗", "SWFFG.HUD.Actions": "行动", "SWFFG.HUD.Maneuvers": "机动", "SWFFG.Sheets.Equipment": "装备", "SWFFG.Sheets.Abilities": "能力", "SWFFG.Sheets.Biography": "背景"
});
setLocale("zh-TW", {
  "TYPES.Actor.character": "角色", "TYPES.Actor.minion": "雜兵組", "TYPES.Actor.rival": "對手", "TYPES.Actor.nemesis": "宿敵", "TYPES.Actor.vehicle": "載具", "TYPES.Actor.group": "小組", "TYPES.Item.weapon": "武器", "TYPES.Item.armor": "護甲", "TYPES.Item.gear": "裝備", "TYPES.Item.talent": "天賦", "TYPES.Item.forcePower": "原力能力", "TYPES.Item.species": "種族", "TYPES.Item.career": "職業", "TYPES.Item.specialization": "專精", "TYPES.Item.signatureAbility": "標誌性能力", "TYPES.Item.attachment": "附件", "TYPES.Item.reference": "參考",
  "SWFFG.System.About": "關於 Star Wars FFG", "SWFFG.Common.Close": "關閉", "SWFFG.Common.Cancel": "取消", "SWFFG.Common.Save": "儲存", "SWFFG.Common.Search": "搜尋", "SWFFG.Common.Open": "開啟", "SWFFG.Common.Record": "記錄", "SWFFG.Common.Apply": "套用", "SWFFG.Common.Back": "返回", "SWFFG.Common.Next": "下一步", "SWFFG.Settings.Groups.CampaignSetup": "戰役設定", "SWFFG.Settings.Groups.Appearance": "外觀", "SWFFG.Settings.Groups.CombatTurns": "戰鬥與回合", "SWFFG.Settings.Groups.PlayTools": "遊戲工具", "SWFFG.Settings.Groups.ImportsSources": "匯入與私人來源", "SWFFG.Settings.Groups.HelpDiagnostics": "說明與診斷", "SWFFG.Settings.Groups.Other": "其他 Star Wars 設定", "SWFFG.HUD.Destiny": "命運", "SWFFG.HUD.Light": "光明", "SWFFG.HUD.Dark": "黑暗", "SWFFG.HUD.Actions": "行動", "SWFFG.HUD.Maneuvers": "機動", "SWFFG.Sheets.Equipment": "裝備", "SWFFG.Sheets.Abilities": "能力", "SWFFG.Sheets.Biography": "背景"
});
setLocale("pl", {
  "TYPES.Actor.character": "Postać", "TYPES.Actor.minion": "Grupa sługusów", "TYPES.Actor.rival": "Rywal", "TYPES.Actor.nemesis": "Nemezis", "TYPES.Actor.vehicle": "Pojazd", "TYPES.Actor.group": "Grupa", "TYPES.Item.weapon": "Broń", "TYPES.Item.armor": "Pancerz", "TYPES.Item.gear": "Wyposażenie", "TYPES.Item.talent": "Talent", "TYPES.Item.forcePower": "Moc", "TYPES.Item.species": "Gatunek", "TYPES.Item.career": "Kariera", "TYPES.Item.specialization": "Specjalizacja", "TYPES.Item.signatureAbility": "Zdolność sygnaturowa", "TYPES.Item.attachment": "Dodatek", "TYPES.Item.reference": "Odnośnik",
  "SWFFG.System.About": "O Star Wars FFG", "SWFFG.Common.Close": "Zamknij", "SWFFG.Common.Cancel": "Anuluj", "SWFFG.Common.Save": "Zapisz", "SWFFG.Common.Search": "Szukaj", "SWFFG.Common.Open": "Otwórz", "SWFFG.Common.Record": "Zapisz wpis", "SWFFG.Common.Apply": "Zastosuj", "SWFFG.Common.Back": "Wstecz", "SWFFG.Common.Next": "Dalej", "SWFFG.Settings.Groups.CampaignSetup": "Ustawienia kampanii", "SWFFG.Settings.Groups.Appearance": "Wygląd", "SWFFG.Settings.Groups.CombatTurns": "Walka i tury", "SWFFG.Settings.Groups.PlayTools": "Narzędzia gry", "SWFFG.Settings.Groups.ImportsSources": "Importy i źródła prywatne", "SWFFG.Settings.Groups.HelpDiagnostics": "Pomoc i diagnostyka", "SWFFG.Settings.Groups.Other": "Inne ustawienia Star Wars", "SWFFG.HUD.Destiny": "Przeznaczenie", "SWFFG.HUD.Light": "Światło", "SWFFG.HUD.Dark": "Ciemność", "SWFFG.HUD.Actions": "Akcje", "SWFFG.HUD.Maneuvers": "Manewry", "SWFFG.Sheets.Equipment": "Wyposażenie", "SWFFG.Sheets.Abilities": "Zdolności", "SWFFG.Sheets.Biography": "Biografia"
});
setLocale("ru", {
  "TYPES.Actor.character": "Персонаж", "TYPES.Actor.minion": "Группа миньонов", "TYPES.Actor.rival": "Соперник", "TYPES.Actor.nemesis": "Немезида", "TYPES.Actor.vehicle": "Транспорт", "TYPES.Actor.group": "Группа", "TYPES.Item.weapon": "Оружие", "TYPES.Item.armor": "Броня", "TYPES.Item.gear": "Снаряжение", "TYPES.Item.talent": "Талант", "TYPES.Item.forcePower": "Сила", "TYPES.Item.species": "Вид", "TYPES.Item.career": "Карьера", "TYPES.Item.specialization": "Специализация", "TYPES.Item.signatureAbility": "Фирменная способность", "TYPES.Item.attachment": "Модификация", "TYPES.Item.reference": "Справка",
  "SWFFG.System.About": "О Star Wars FFG", "SWFFG.Common.Close": "Закрыть", "SWFFG.Common.Cancel": "Отмена", "SWFFG.Common.Save": "Сохранить", "SWFFG.Common.Search": "Поиск", "SWFFG.Common.Open": "Открыть", "SWFFG.Common.Record": "Записать", "SWFFG.Common.Apply": "Применить", "SWFFG.Common.Back": "Назад", "SWFFG.Common.Next": "Далее", "SWFFG.Settings.Groups.CampaignSetup": "Настройка кампании", "SWFFG.Settings.Groups.Appearance": "Внешний вид", "SWFFG.Settings.Groups.CombatTurns": "Бой и ходы", "SWFFG.Settings.Groups.PlayTools": "Игровые инструменты", "SWFFG.Settings.Groups.ImportsSources": "Импорт и частные источники", "SWFFG.Settings.Groups.HelpDiagnostics": "Помощь и диагностика", "SWFFG.Settings.Groups.Other": "Другие настройки Star Wars", "SWFFG.HUD.Destiny": "Судьба", "SWFFG.HUD.Light": "Свет", "SWFFG.HUD.Dark": "Тьма", "SWFFG.HUD.Actions": "Действия", "SWFFG.HUD.Maneuvers": "Манёвры", "SWFFG.Sheets.Equipment": "Снаряжение", "SWFFG.Sheets.Abilities": "Способности", "SWFFG.Sheets.Biography": "Биография"
});
setLocale("nl", {
  "TYPES.Actor.character": "Personage", "TYPES.Actor.minion": "Miniongroep", "TYPES.Actor.rival": "Rivaal", "TYPES.Actor.nemesis": "Nemesis", "TYPES.Actor.vehicle": "Voertuig", "TYPES.Actor.group": "Groep", "TYPES.Item.weapon": "Wapen", "TYPES.Item.armor": "Pantser", "TYPES.Item.gear": "Uitrusting", "TYPES.Item.talent": "Talent", "TYPES.Item.forcePower": "Krachtvermogen", "TYPES.Item.species": "Soort", "TYPES.Item.career": "Carrière", "TYPES.Item.specialization": "Specialisatie", "TYPES.Item.signatureAbility": "Kenmerkende vaardigheid", "TYPES.Item.attachment": "Hulpstuk", "TYPES.Item.reference": "Referentie",
  "SWFFG.System.About": "Over Star Wars FFG", "SWFFG.Common.Close": "Sluiten", "SWFFG.Common.Cancel": "Annuleren", "SWFFG.Common.Save": "Opslaan", "SWFFG.Common.Search": "Zoeken", "SWFFG.Common.Open": "Openen", "SWFFG.Common.Record": "Vastleggen", "SWFFG.Common.Apply": "Toepassen", "SWFFG.Common.Back": "Terug", "SWFFG.Common.Next": "Volgende", "SWFFG.Settings.Groups.CampaignSetup": "Campagne-instellingen", "SWFFG.Settings.Groups.Appearance": "Uiterlijk", "SWFFG.Settings.Groups.CombatTurns": "Gevecht en beurten", "SWFFG.Settings.Groups.PlayTools": "Spelhulpmiddelen", "SWFFG.Settings.Groups.ImportsSources": "Import en privébronnen", "SWFFG.Settings.Groups.HelpDiagnostics": "Hulp en diagnose", "SWFFG.Settings.Groups.Other": "Andere Star Wars-instellingen", "SWFFG.HUD.Destiny": "Bestemming", "SWFFG.HUD.Light": "Licht", "SWFFG.HUD.Dark": "Donker", "SWFFG.HUD.Actions": "Acties", "SWFFG.HUD.Maneuvers": "Manoeuvres", "SWFFG.Sheets.Equipment": "Uitrusting", "SWFFG.Sheets.Abilities": "Vaardigheden", "SWFFG.Sheets.Biography": "Biografie"
});
setLocale("sv", {
  "TYPES.Actor.character": "Rollperson", "TYPES.Actor.minion": "Grupp av hantlangare", "TYPES.Actor.rival": "Rival", "TYPES.Actor.nemesis": "Nemesis", "TYPES.Actor.vehicle": "Fordon", "TYPES.Actor.group": "Grupp", "TYPES.Item.weapon": "Vapen", "TYPES.Item.armor": "Rustning", "TYPES.Item.gear": "Utrustning", "TYPES.Item.talent": "Talang", "TYPES.Item.forcePower": "Kraftförmåga", "TYPES.Item.species": "Art", "TYPES.Item.career": "Karriär", "TYPES.Item.specialization": "Specialisering", "TYPES.Item.signatureAbility": "Signaturförmåga", "TYPES.Item.attachment": "Tillbehör", "TYPES.Item.reference": "Referens",
  "SWFFG.System.About": "Om Star Wars FFG", "SWFFG.Common.Close": "Stäng", "SWFFG.Common.Cancel": "Avbryt", "SWFFG.Common.Save": "Spara", "SWFFG.Common.Search": "Sök", "SWFFG.Common.Open": "Öppna", "SWFFG.Common.Record": "Registrera", "SWFFG.Common.Apply": "Tillämpa", "SWFFG.Common.Back": "Tillbaka", "SWFFG.Common.Next": "Nästa", "SWFFG.Settings.Groups.CampaignSetup": "Kampanjinställningar", "SWFFG.Settings.Groups.Appearance": "Utseende", "SWFFG.Settings.Groups.CombatTurns": "Strid och rundor", "SWFFG.Settings.Groups.PlayTools": "Spelverktyg", "SWFFG.Settings.Groups.ImportsSources": "Import och privata källor", "SWFFG.Settings.Groups.HelpDiagnostics": "Hjälp och diagnostik", "SWFFG.Settings.Groups.Other": "Övriga Star Wars-inställningar", "SWFFG.HUD.Destiny": "Öde", "SWFFG.HUD.Light": "Ljus", "SWFFG.HUD.Dark": "Mörker", "SWFFG.HUD.Actions": "Handlingar", "SWFFG.HUD.Maneuvers": "Manövrer", "SWFFG.Sheets.Equipment": "Utrustning", "SWFFG.Sheets.Abilities": "Förmågor", "SWFFG.Sheets.Biography": "Biografi"
});

// Static sheet labels are translated for every shipped locale. Longer
// guidance remains available from the English source value until an editor
// supplies a language-specific wording; the key is still present everywhere.
const ui = (locale, values) =>
  setLocale(
    locale,
    Object.fromEntries(
      Object.entries(values).map(([key, value]) => [`SWFFG.UI.${key}`, value]),
    ),
  );
ui("es", {
  Brand: "STAR WARS FFG", NarrativeToolkit: "HERRAMIENTAS NARRATIVAS", GroupRecord: "REGISTRO DEL GRUPO", SheetTheme: "Tema de hoja", Portrait: "Retrato", Name: "Nombre", Model: "Modelo", Manufacturer: "Fabricante", Registration: "Matrícula", Species: "Especie", Career: "Carrera", CampaignRules: "Reglas de campaña", HomebrewSetup: "Configuración casera", CreateCharacter: "Crear este personaje", ManualCreation: "Creación manual", GuidedCreation: "Guiarme", BuildEnemy: "Crear un enemigo", EnemyGuide: "Guía de enemigos", ReadyForPlay: "Listo para jugar", CharacterSections: "Secciones del personaje", Characteristics: "Características", Condition: "Condición", Vitals: "Vitales", Current: "Actual", Threshold: "Umbral", ApplyDamage: "Aplicar daño", Speed: "Velocidad", Credits: "Créditos", RollForce: "Tirar Fuerza", DeflectorShields: "Escudos deflectores", Crew: "Tripulación", Passengers: "Pasajeros", Cargo: "Carga", Obligation: "Obligación", Duty: "Deber", Morality: "Moralidad", MinionGroup: "Grupo de esbirros", Skills: "Habilidades", Equipment: "Equipo", Abilities: "Habilidades especiales", AddItem: "Añadir objeto", View: "Ver", Open: "Abrir", AdvancementRecord: "Registro de avance", Logbook: "Diario", StoryHooks: "Ganchos de historia", BackgroundStory: "Historia de trasfondo", Motivations: "Motivaciones", Add: "Añadir", BioNotes: "Notas biográficas", SourceReference: "Referencia de fuente", Book: "Libro", Page: "Página", SharedDestiny: "Destino compartido", DiceDestiny: "Dados y Destino", GroupMembers: "Miembros del grupo", AddMember: "Añadir miembro", StartingGroupAsset: "Recurso inicial del grupo", SharedResourceLedger: "Libro de recursos compartidos", RecordResourceChange: "Registrar cambio", Search: "Buscar", Previous: "Anterior", Next: "Siguiente", Table: "Tabla", Result: "Resultado", SupportStart: "Comenzar aquí", Status: "Estado", ValidateFields: "Validar campos", SaveReviewedData: "Guardar datos revisados"
});
ui("fr", {
  Brand: "STAR WARS FFG", NarrativeToolkit: "OUTILS NARRATIFS", GroupRecord: "FICHE DU GROUPE", SheetTheme: "Thème de fiche", Portrait: "Portrait", Name: "Nom", Model: "Modèle", Manufacturer: "Fabricant", Registration: "Immatriculation", Species: "Espèce", Career: "Carrière", CampaignRules: "Règles de campagne", HomebrewSetup: "Configuration personnalisée", CreateCharacter: "Créer ce personnage", ManualCreation: "Création manuelle", GuidedCreation: "Me guider", BuildEnemy: "Créer un adversaire", EnemyGuide: "Guide des adversaires", ReadyForPlay: "Prêt à jouer", CharacterSections: "Sections du personnage", Characteristics: "Caractéristiques", Condition: "État", Vitals: "Vitalité", Current: "Actuel", Threshold: "Seuil", ApplyDamage: "Appliquer les dégâts", Speed: "Vitesse", Credits: "Crédits", RollForce: "Lancer la Force", DeflectorShields: "Boucliers déflecteurs", Crew: "Équipage", Passengers: "Passagers", Cargo: "Cargaison", Obligation: "Obligation", Duty: "Devoir", Morality: "Moralité", MinionGroup: "Groupe de sbires", Skills: "Compétences", Equipment: "Équipement", Abilities: "Capacités", AddItem: "Ajouter un objet", View: "Voir", Open: "Ouvrir", AdvancementRecord: "Historique de progression", Logbook: "Journal", StoryHooks: "Accroches narratives", BackgroundStory: "Histoire personnelle", Motivations: "Motivations", Add: "Ajouter", BioNotes: "Notes biographiques", SourceReference: "Référence de source", Book: "Livre", Page: "Page", SharedDestiny: "Destin partagé", DiceDestiny: "Dés et Destin", GroupMembers: "Membres du groupe", AddMember: "Ajouter un membre", StartingGroupAsset: "Ressource initiale du groupe", SharedResourceLedger: "Registre des ressources partagées", RecordResourceChange: "Enregistrer un changement", Search: "Rechercher", Previous: "Précédent", Next: "Suivant", Table: "Table", Result: "Résultat", SupportStart: "Commencer ici", Status: "État", ValidateFields: "Valider les champs", SaveReviewedData: "Enregistrer les données vérifiées"
});
ui("de", {
  Brand: "STAR WARS FFG", NarrativeToolkit: "NARRATIVES WERKZEUG", GroupRecord: "GRUPPENPROTOKOLL", SheetTheme: "Bogenstil", Portrait: "Porträt", Name: "Name", Model: "Modell", Manufacturer: "Hersteller", Registration: "Registrierung", Species: "Spezies", Career: "Karriere", CampaignRules: "Kampagnenregeln", HomebrewSetup: "Hausregel-Einrichtung", CreateCharacter: "Diesen Charakter erstellen", ManualCreation: "Manuelle Erstellung", GuidedCreation: "Mich führen", BuildEnemy: "Gegner erstellen", EnemyGuide: "Gegnerleitfaden", ReadyForPlay: "Spielbereit", CharacterSections: "Charakterbereiche", Characteristics: "Eigenschaften", Condition: "Zustand", Vitals: "Lebenspunkte", Current: "Aktuell", Threshold: "Schwelle", ApplyDamage: "Schaden anwenden", Speed: "Geschwindigkeit", Credits: "Credits", RollForce: "Macht würfeln", DeflectorShields: "Deflektorschilde", Crew: "Besatzung", Passengers: "Passagiere", Cargo: "Fracht", Obligation: "Verpflichtung", Duty: "Aufgabe", Morality: "Moral", MinionGroup: "Schergengruppe", Skills: "Fertigkeiten", Equipment: "Ausrüstung", Abilities: "Fähigkeiten", AddItem: "Gegenstand hinzufügen", View: "Anzeigen", Open: "Öffnen", AdvancementRecord: "Fortschrittsprotokoll", Logbook: "Logbuch", StoryHooks: "Handlungsaufhänger", BackgroundStory: "Hintergrundgeschichte", Motivations: "Motivationen", Add: "Hinzufügen", BioNotes: "Biografische Notizen", SourceReference: "Quellenangabe", Book: "Buch", Page: "Seite", SharedDestiny: "Geteiltes Schicksal", DiceDestiny: "Würfel und Schicksal", GroupMembers: "Gruppenmitglieder", AddMember: "Mitglied hinzufügen", StartingGroupAsset: "Startressource der Gruppe", SharedResourceLedger: "Register gemeinsamer Ressourcen", RecordResourceChange: "Änderung aufzeichnen", Search: "Suchen", Previous: "Zurück", Next: "Weiter", Table: "Tabelle", Result: "Ergebnis", SupportStart: "Hier beginnen", Status: "Status", ValidateFields: "Felder prüfen", SaveReviewedData: "Geprüfte Daten speichern"
});
ui("it", {
  Brand: "STAR WARS FFG", NarrativeToolkit: "STRUMENTI NARRATIVI", GroupRecord: "SCHEDA DEL GRUPPO", SheetTheme: "Tema della scheda", Portrait: "Ritratto", Name: "Nome", Model: "Modello", Manufacturer: "Produttore", Registration: "Registrazione", Species: "Specie", Career: "Carriera", CampaignRules: "Regole della campagna", HomebrewSetup: "Configurazione personalizzata", CreateCharacter: "Crea questo personaggio", ManualCreation: "Creazione manuale", GuidedCreation: "Guidami", BuildEnemy: "Crea un nemico", EnemyGuide: "Guida ai nemici", ReadyForPlay: "Pronto per il gioco", CharacterSections: "Sezioni del personaggio", Characteristics: "Caratteristiche", Condition: "Condizione", Vitals: "Integrità", Current: "Attuale", Threshold: "Soglia", ApplyDamage: "Applica danni", Speed: "Velocità", Credits: "Crediti", RollForce: "Tira la Forza", DeflectorShields: "Scudi deflettori", Crew: "Equipaggio", Passengers: "Passeggeri", Cargo: "Carico", Obligation: "Obbligo", Duty: "Dovere", Morality: "Moralità", MinionGroup: "Gruppo di minion", Skills: "Abilità", Equipment: "Equipaggiamento", Abilities: "Capacità", AddItem: "Aggiungi oggetto", View: "Visualizza", Open: "Apri", AdvancementRecord: "Registro avanzamento", Logbook: "Diario", StoryHooks: "Spunti narrativi", BackgroundStory: "Storia personale", Motivations: "Motivazioni", Add: "Aggiungi", BioNotes: "Note biografiche", SourceReference: "Riferimento della fonte", Book: "Libro", Page: "Pagina", SharedDestiny: "Destino condiviso", DiceDestiny: "Dadi e Destino", GroupMembers: "Membri del gruppo", AddMember: "Aggiungi membro", StartingGroupAsset: "Risorsa iniziale del gruppo", SharedResourceLedger: "Registro risorse condivise", RecordResourceChange: "Registra modifica", Search: "Cerca", Previous: "Precedente", Next: "Successivo", Table: "Tabella", Result: "Risultato", SupportStart: "Inizia qui", Status: "Stato", ValidateFields: "Convalida campi", SaveReviewedData: "Salva dati verificati"
});
ui("pt-BR", {
  Brand: "STAR WARS FFG", NarrativeToolkit: "FERRAMENTAS NARRATIVAS", GroupRecord: "REGISTRO DO GRUPO", SheetTheme: "Tema da ficha", Portrait: "Retrato", Name: "Nome", Model: "Modelo", Manufacturer: "Fabricante", Registration: "Registro", Species: "Espécie", Career: "Carreira", CampaignRules: "Regras da campanha", HomebrewSetup: "Configuração caseira", CreateCharacter: "Criar este personagem", ManualCreation: "Criação manual", GuidedCreation: "Guiar-me", BuildEnemy: "Criar um inimigo", EnemyGuide: "Guia de inimigos", ReadyForPlay: "Pronto para jogar", CharacterSections: "Seções do personagem", Characteristics: "Características", Condition: "Condição", Vitals: "Vitalidade", Current: "Atual", Threshold: "Limite", ApplyDamage: "Aplicar dano", Speed: "Velocidade", Credits: "Créditos", RollForce: "Rolar Força", DeflectorShields: "Escudos defletores", Crew: "Tripulação", Passengers: "Passageiros", Cargo: "Carga", Obligation: "Obrigação", Duty: "Dever", Morality: "Moralidade", MinionGroup: "Grupo de lacaios", Skills: "Perícias", Equipment: "Equipamento", Abilities: "Habilidades", AddItem: "Adicionar item", View: "Ver", Open: "Abrir", AdvancementRecord: "Registro de avanço", Logbook: "Diário", StoryHooks: "Ganchos narrativos", BackgroundStory: "História de fundo", Motivations: "Motivações", Add: "Adicionar", BioNotes: "Notas biográficas", SourceReference: "Referência da fonte", Book: "Livro", Page: "Página", SharedDestiny: "Destino compartilhado", DiceDestiny: "Dados e Destino", GroupMembers: "Membros do grupo", AddMember: "Adicionar membro", StartingGroupAsset: "Recurso inicial do grupo", SharedResourceLedger: "Livro de recursos compartilhados", RecordResourceChange: "Registrar mudança", Search: "Pesquisar", Previous: "Anterior", Next: "Próximo", Table: "Tabela", Result: "Resultado", SupportStart: "Comece aqui", Status: "Status", ValidateFields: "Validar campos", SaveReviewedData: "Salvar dados revisados"
});
ui("pt-PT", {
  Brand: "STAR WARS FFG", NarrativeToolkit: "FERRAMENTAS NARRATIVAS", GroupRecord: "REGISTO DO GRUPO", SheetTheme: "Tema da ficha", Portrait: "Retrato", Name: "Nome", Model: "Modelo", Manufacturer: "Fabricante", Registration: "Registo", Species: "Espécie", Career: "Carreira", CampaignRules: "Regras da campanha", HomebrewSetup: "Configuração caseira", CreateCharacter: "Criar esta personagem", ManualCreation: "Criação manual", GuidedCreation: "Guiar-me", BuildEnemy: "Criar um inimigo", EnemyGuide: "Guia de inimigos", ReadyForPlay: "Pronto para jogar", CharacterSections: "Secções da personagem", Characteristics: "Características", Condition: "Condição", Vitals: "Vitalidade", Current: "Atual", Threshold: "Limiar", ApplyDamage: "Aplicar dano", Speed: "Velocidade", Credits: "Créditos", RollForce: "Rolar Força", DeflectorShields: "Escudos defletores", Crew: "Tripulação", Passengers: "Passageiros", Cargo: "Carga", Obligation: "Obrigação", Duty: "Dever", Morality: "Moralidade", MinionGroup: "Grupo de lacaios", Skills: "Perícias", Equipment: "Equipamento", Abilities: "Habilidades", AddItem: "Adicionar item", View: "Ver", Open: "Abrir", AdvancementRecord: "Registo de progressão", Logbook: "Diário", StoryHooks: "Ganchos narrativos", BackgroundStory: "História de fundo", Motivations: "Motivações", Add: "Adicionar", BioNotes: "Notas biográficas", SourceReference: "Referência da fonte", Book: "Livro", Page: "Página", SharedDestiny: "Destino partilhado", DiceDestiny: "Dados e Destino", GroupMembers: "Membros do grupo", AddMember: "Adicionar membro", StartingGroupAsset: "Recurso inicial do grupo", SharedResourceLedger: "Registo de recursos partilhados", RecordResourceChange: "Registar alteração", Search: "Pesquisar", Previous: "Anterior", Next: "Seguinte", Table: "Tabela", Result: "Resultado", SupportStart: "Começar aqui", Status: "Estado", ValidateFields: "Validar campos", SaveReviewedData: "Guardar dados verificados"
});
ui("ja", {
  NarrativeToolkit: "ナラティブ・ツールキット", GroupRecord: "グループ記録", SheetTheme: "シートテーマ", Portrait: "ポートレート", Name: "名前", Model: "モデル", Manufacturer: "メーカー", Registration: "登録番号", Species: "種族", Career: "キャリア", CampaignRules: "キャンペーンルール", HomebrewSetup: "ホームブリュー設定", CreateCharacter: "このキャラクターを作成", ManualCreation: "手動作成", GuidedCreation: "案内して", BuildEnemy: "敵を作成", EnemyGuide: "敵ガイド", ReadyForPlay: "プレイ準備完了", CharacterSections: "キャラクター項目", Characteristics: "特性", Condition: "状態", Vitals: "生命値", Current: "現在値", Threshold: "しきい値", ApplyDamage: "ダメージを適用", Speed: "速度", Credits: "クレジット", RollForce: "フォースを振る", DeflectorShields: "偏向シールド", Crew: "乗組員", Passengers: "乗客", Cargo: "貨物", Obligation: "義務", Duty: "任務", Morality: "道徳", MinionGroup: "ミニオン・グループ", Skills: "スキル", Equipment: "装備", Abilities: "アビリティ", AddItem: "アイテムを追加", View: "表示", Open: "開く", AdvancementRecord: "成長記録", Logbook: "ログブック", StoryHooks: "ストーリーフック", BackgroundStory: "背景ストーリー", Motivations: "動機", Add: "追加", BioNotes: "人物メモ", SourceReference: "出典", Book: "書籍", Page: "ページ", SharedDestiny: "共有Destiny", DiceDestiny: "ダイスとDestiny", GroupMembers: "グループメンバー", AddMember: "メンバーを追加", StartingGroupAsset: "グループ開始資産", SharedResourceLedger: "共有リソース台帳", RecordResourceChange: "変更を記録", Search: "検索", Previous: "前へ", Next: "次へ", Table: "表", Result: "結果", SupportStart: "ここから開始", Status: "状態", ValidateFields: "フィールドを検証", SaveReviewedData: "確認済みデータを保存"
});
ui("ko", {
  NarrativeToolkit: "내러티브 도구", GroupRecord: "그룹 기록", SheetTheme: "시트 테마", Portrait: "초상화", Name: "이름", Model: "모델", Manufacturer: "제조사", Registration: "등록", Species: "종족", Career: "커리어", CampaignRules: "캠페인 규칙", HomebrewSetup: "홈브루 설정", CreateCharacter: "이 캐릭터 만들기", ManualCreation: "수동 생성", GuidedCreation: "안내 받기", BuildEnemy: "적 만들기", EnemyGuide: "적 가이드", ReadyForPlay: "플레이 준비 완료", CharacterSections: "캐릭터 섹션", Characteristics: "특성", Condition: "상태", Vitals: "생명력", Current: "현재", Threshold: "한계치", ApplyDamage: "피해 적용", Speed: "속도", Credits: "크레딧", RollForce: "포스 굴리기", DeflectorShields: "디플렉터 실드", Crew: "승무원", Passengers: "승객", Cargo: "화물", Obligation: "의무", Duty: "임무", Morality: "도덕성", MinionGroup: "미니언 그룹", Skills: "기술", Equipment: "장비", Abilities: "능력", AddItem: "아이템 추가", View: "보기", Open: "열기", AdvancementRecord: "성장 기록", Logbook: "로그북", StoryHooks: "스토리 훅", BackgroundStory: "배경 이야기", Motivations: "동기", Add: "추가", BioNotes: "인물 메모", SourceReference: "출처", Book: "서적", Page: "페이지", SharedDestiny: "공유 Destiny", DiceDestiny: "주사위와 Destiny", GroupMembers: "그룹 구성원", AddMember: "구성원 추가", StartingGroupAsset: "그룹 시작 자산", SharedResourceLedger: "공유 자원 원장", RecordResourceChange: "변경 기록", Search: "검색", Previous: "이전", Next: "다음", Table: "표", Result: "결과", SupportStart: "여기서 시작", Status: "상태", ValidateFields: "필드 검증", SaveReviewedData: "검토한 데이터 저장"
});
ui("zh-CN", {
  NarrativeToolkit: "叙事工具包", GroupRecord: "小组记录", SheetTheme: "角色卡主题", Portrait: "肖像", Name: "名称", Model: "型号", Manufacturer: "制造商", Registration: "登记号", Species: "种族", Career: "职业", CampaignRules: "战役规则", HomebrewSetup: "自定义设置", CreateCharacter: "创建此角色", ManualCreation: "手动创建", GuidedCreation: "引导我", BuildEnemy: "创建敌人", EnemyGuide: "敌人向导", ReadyForPlay: "准备开始游戏", CharacterSections: "角色分区", Characteristics: "特性", Condition: "状态", Vitals: "生命值", Current: "当前", Threshold: "阈值", ApplyDamage: "应用伤害", Speed: "速度", Credits: "信用点", RollForce: "投掷原力", DeflectorShields: "偏导护盾", Crew: "船员", Passengers: "乘客", Cargo: "货物", Obligation: "义务", Duty: "职责", Morality: "道德", MinionGroup: "杂兵组", Skills: "技能", Equipment: "装备", Abilities: "能力", AddItem: "添加物品", View: "查看", Open: "打开", AdvancementRecord: "成长记录", Logbook: "日志", StoryHooks: "故事钩子", BackgroundStory: "背景故事", Motivations: "动机", Add: "添加", BioNotes: "传记备注", SourceReference: "来源参考", Book: "书籍", Page: "页码", SharedDestiny: "共享命运", DiceDestiny: "骰子与命运", GroupMembers: "小组成员", AddMember: "添加成员", StartingGroupAsset: "小组起始资源", SharedResourceLedger: "共享资源账本", RecordResourceChange: "记录变更", Search: "搜索", Previous: "上一页", Next: "下一页", Table: "表格", Result: "结果", SupportStart: "从这里开始", Status: "状态", ValidateFields: "验证字段", SaveReviewedData: "保存已审阅数据"
});
ui("zh-TW", {
  NarrativeToolkit: "敘事工具包", GroupRecord: "小組記錄", SheetTheme: "角色卡主題", Portrait: "肖像", Name: "名稱", Model: "型號", Manufacturer: "製造商", Registration: "登記號", Species: "種族", Career: "職業", CampaignRules: "戰役規則", HomebrewSetup: "自訂設定", CreateCharacter: "建立此角色", ManualCreation: "手動建立", GuidedCreation: "引導我", BuildEnemy: "建立敵人", EnemyGuide: "敵人精靈", ReadyForPlay: "準備開始遊戲", CharacterSections: "角色區段", Characteristics: "特性", Condition: "狀態", Vitals: "生命值", Current: "目前", Threshold: "閾值", ApplyDamage: "套用傷害", Speed: "速度", Credits: "信用點", RollForce: "擲原力", DeflectorShields: "偏導護盾", Crew: "船員", Passengers: "乘客", Cargo: "貨物", Obligation: "義務", Duty: "職責", Morality: "道德", MinionGroup: "雜兵組", Skills: "技能", Equipment: "裝備", Abilities: "能力", AddItem: "新增物品", View: "檢視", Open: "開啟", AdvancementRecord: "成長記錄", Logbook: "日誌", StoryHooks: "故事鉤子", BackgroundStory: "背景故事", Motivations: "動機", Add: "新增", BioNotes: "傳記備註", SourceReference: "來源參考", Book: "書籍", Page: "頁碼", SharedDestiny: "共享命運", DiceDestiny: "骰子與命運", GroupMembers: "小組成員", AddMember: "新增成員", StartingGroupAsset: "小組起始資源", SharedResourceLedger: "共享資源帳本", RecordResourceChange: "記錄變更", Search: "搜尋", Previous: "上一頁", Next: "下一頁", Table: "表格", Result: "結果", SupportStart: "從這裡開始", Status: "狀態", ValidateFields: "驗證欄位", SaveReviewedData: "儲存已審閱資料"
});
ui("pl", {
  NarrativeToolkit: "NARZĘDZIA NARRACYJNE", GroupRecord: "REJESTR GRUPY", SheetTheme: "Motyw karty", Portrait: "Portret", Name: "Nazwa", Model: "Model", Manufacturer: "Producent", Registration: "Rejestracja", Species: "Gatunek", Career: "Kariera", CampaignRules: "Zasady kampanii", HomebrewSetup: "Konfiguracja własna", CreateCharacter: "Utwórz tę postać", ManualCreation: "Tworzenie ręczne", GuidedCreation: "Prowadź mnie", BuildEnemy: "Utwórz wroga", EnemyGuide: "Przewodnik wrogów", ReadyForPlay: "Gotowe do gry", CharacterSections: "Sekcje postaci", Characteristics: "Cechy", Condition: "Stan", Vitals: "Żywotność", Current: "Bieżące", Threshold: "Próg", ApplyDamage: "Zastosuj obrażenia", Speed: "Prędkość", Credits: "Kredyty", RollForce: "Rzuć Moc", DeflectorShields: "Tarcze deflektora", Crew: "Załoga", Passengers: "Pasażerowie", Cargo: "Ładunek", Obligation: "Obowiązek", Duty: "Służba", Morality: "Moralność", MinionGroup: "Grupa sługusów", Skills: "Umiejętności", Equipment: "Wyposażenie", Abilities: "Zdolności", AddItem: "Dodaj przedmiot", View: "Wyświetl", Open: "Otwórz", AdvancementRecord: "Rejestr rozwoju", Logbook: "Dziennik", StoryHooks: "Haki fabularne", BackgroundStory: "Historia tła", Motivations: "Motywacje", Add: "Dodaj", BioNotes: "Notatki biograficzne", SourceReference: "Źródło", Book: "Książka", Page: "Strona", SharedDestiny: "Wspólne Przeznaczenie", DiceDestiny: "Kości i Przeznaczenie", GroupMembers: "Członkowie grupy", AddMember: "Dodaj członka", StartingGroupAsset: "Zasób początkowy grupy", SharedResourceLedger: "Rejestr wspólnych zasobów", RecordResourceChange: "Zapisz zmianę", Search: "Szukaj", Previous: "Poprzedni", Next: "Dalej", Table: "Tabela", Result: "Wynik", SupportStart: "Zacznij tutaj", Status: "Status", ValidateFields: "Sprawdź pola", SaveReviewedData: "Zapisz sprawdzone dane"
});
ui("ru", {
  NarrativeToolkit: "НАРРАТИВНЫЕ ИНСТРУМЕНТЫ", GroupRecord: "ЗАПИСЬ ГРУППЫ", SheetTheme: "Тема листа", Portrait: "Портрет", Name: "Имя", Model: "Модель", Manufacturer: "Производитель", Registration: "Регистрация", Species: "Вид", Career: "Карьера", CampaignRules: "Правила кампании", HomebrewSetup: "Настройка хоумбрю", CreateCharacter: "Создать персонажа", ManualCreation: "Ручное создание", GuidedCreation: "Провести меня", BuildEnemy: "Создать врага", EnemyGuide: "Справочник врагов", ReadyForPlay: "Готов к игре", CharacterSections: "Разделы персонажа", Characteristics: "Характеристики", Condition: "Состояние", Vitals: "Жизнь", Current: "Текущее", Threshold: "Порог", ApplyDamage: "Нанести урон", Speed: "Скорость", Credits: "Кредиты", RollForce: "Бросить Силу", DeflectorShields: "Дефлекторные щиты", Crew: "Экипаж", Passengers: "Пассажиры", Cargo: "Груз", Obligation: "Обязательство", Duty: "Служба", Morality: "Мораль", MinionGroup: "Группа миньонов", Skills: "Навыки", Equipment: "Снаряжение", Abilities: "Способности", AddItem: "Добавить предмет", View: "Просмотр", Open: "Открыть", AdvancementRecord: "Журнал развития", Logbook: "Журнал", StoryHooks: "Сюжетные зацепки", BackgroundStory: "Предыстория", Motivations: "Мотивации", Add: "Добавить", BioNotes: "Биографические заметки", SourceReference: "Источник", Book: "Книга", Page: "Страница", SharedDestiny: "Общая Судьба", DiceDestiny: "Кости и Судьба", GroupMembers: "Участники группы", AddMember: "Добавить участника", StartingGroupAsset: "Начальный ресурс группы", SharedResourceLedger: "Журнал общих ресурсов", RecordResourceChange: "Записать изменение", Search: "Поиск", Previous: "Назад", Next: "Далее", Table: "Таблица", Result: "Результат", SupportStart: "Начать здесь", Status: "Статус", ValidateFields: "Проверить поля", SaveReviewedData: "Сохранить проверенные данные"
});
ui("nl", {
  NarrativeToolkit: "NARRATIEVE HULPMIDDELEN", GroupRecord: "GROEPSREGISTRATIE", SheetTheme: "Bladthema", Portrait: "Portret", Name: "Naam", Model: "Model", Manufacturer: "Fabrikant", Registration: "Registratie", Species: "Soort", Career: "Carrière", CampaignRules: "Campagneregels", HomebrewSetup: "Homebrew-instelling", CreateCharacter: "Dit personage maken", ManualCreation: "Handmatig maken", GuidedCreation: "Begeleiden", BuildEnemy: "Vijand maken", EnemyGuide: "Vijandengids", ReadyForPlay: "Klaar om te spelen", CharacterSections: "Personagesecties", Characteristics: "Eigenschappen", Condition: "Toestand", Vitals: "Levenspunten", Current: "Huidig", Threshold: "Drempel", ApplyDamage: "Schade toepassen", Speed: "Snelheid", Credits: "Credits", RollForce: "Kracht werpen", DeflectorShields: "Deflectorschilden", Crew: "Bemanning", Passengers: "Passagiers", Cargo: "Lading", Obligation: "Verplichting", Duty: "Plicht", Morality: "Moraliteit", MinionGroup: "Miniongroep", Skills: "Vaardigheden", Equipment: "Uitrusting", Abilities: "Vermogens", AddItem: "Item toevoegen", View: "Bekijken", Open: "Openen", AdvancementRecord: "Voortgangsregistratie", Logbook: "Logboek", StoryHooks: "Verhaalhaken", BackgroundStory: "Achtergrondverhaal", Motivations: "Motivaties", Add: "Toevoegen", BioNotes: "Biografische notities", SourceReference: "Bronverwijzing", Book: "Boek", Page: "Pagina", SharedDestiny: "Gedeeld Lot", DiceDestiny: "Dobbelstenen en Lot", GroupMembers: "Groepsleden", AddMember: "Lid toevoegen", StartingGroupAsset: "Startmiddel van de groep", SharedResourceLedger: "Register gedeelde middelen", RecordResourceChange: "Wijziging vastleggen", Search: "Zoeken", Previous: "Vorige", Next: "Volgende", Table: "Tabel", Result: "Resultaat", SupportStart: "Begin hier", Status: "Status", ValidateFields: "Velden valideren", SaveReviewedData: "Beoordeelde gegevens opslaan"
});
ui("sv", {
  NarrativeToolkit: "NARRATIVA VERKTYG", GroupRecord: "GRUPPREGISTER", SheetTheme: "Bladtema", Portrait: "Porträtt", Name: "Namn", Model: "Modell", Manufacturer: "Tillverkare", Registration: "Registrering", Species: "Art", Career: "Karriär", CampaignRules: "Kampanjregler", HomebrewSetup: "Egen inställning", CreateCharacter: "Skapa denna rollperson", ManualCreation: "Manuell skapelse", GuidedCreation: "Vägled mig", BuildEnemy: "Skapa en fiende", EnemyGuide: "Fiendeguide", ReadyForPlay: "Redo att spela", CharacterSections: "Rollpersonens delar", Characteristics: "Egenskaper", Condition: "Tillstånd", Vitals: "Livskraft", Current: "Aktuellt", Threshold: "Tröskel", ApplyDamage: "Tillämpa skada", Speed: "Hastighet", Credits: "Krediter", RollForce: "Slå Kraft", DeflectorShields: "Deflektorsköldar", Crew: "Besättning", Passengers: "Passagerare", Cargo: "Last", Obligation: "Förpliktelse", Duty: "Tjänst", Morality: "Moral", MinionGroup: "Hantlangargrupp", Skills: "Färdigheter", Equipment: "Utrustning", Abilities: "Förmågor", AddItem: "Lägg till föremål", View: "Visa", Open: "Öppna", AdvancementRecord: "Utvecklingsregister", Logbook: "Loggbok", StoryHooks: "Berättelsekrokar", BackgroundStory: "Bakgrundshistoria", Motivations: "Motivationer", Add: "Lägg till", BioNotes: "Biografiska anteckningar", SourceReference: "Källreferens", Book: "Bok", Page: "Sida", SharedDestiny: "Delat öde", DiceDestiny: "Tärningar och öde", GroupMembers: "Gruppmedlemmar", AddMember: "Lägg till medlem", StartingGroupAsset: "Gruppens startresurs", SharedResourceLedger: "Register över gemensamma resurser", RecordResourceChange: "Registrera ändring", Search: "Sök", Previous: "Föregående", Next: "Nästa", Table: "Tabell", Result: "Resultat", SupportStart: "Börja här", Status: "Status", ValidateFields: "Validera fält", SaveReviewedData: "Spara granskade data"
});
ui("en-GB", { SheetTheme: "Sheet theme", FooterRulebooks: "Independent tooling · Keep the rulebooks at the table", PurchaseCharacteristic: "Purchase next characteristic rating with XP" });
ui("en-US", { SheetTheme: "Sheet theme", FooterRulebooks: "Independent tooling · Keep the rulebooks at the table" });
ui("es", { SessionConsole: "Consola de sesión", RollPool: "Tirar reserva", UseLight: "Usar luz", UseDark: "Usar oscuridad", SeedDestiny: "Sembrar Destino", DefaultSheetTheme: "Tema de hoja predeterminado", FoundryInterfaceTheme: "Tema de interfaz de Foundry", CompactDiceTray: "Bandeja de dados compacta junto al chat", TransactionAuthority: "Autoridad de transacciones", UseThisGmTab: "Usar esta pestaña del DJ", GmSourceKey: "Clave de fuentes del DJ", BackupRestoreKey: "Respaldar o restaurar clave", GmSourceLibrary: "Biblioteca de fuentes del DJ", SearchPrivateSources: "Buscar fuentes privadas", CampaignRulesAdventure: "Reglas de campaña y estado de aventura", ChooseCampaignRules: "Elegir reglas de campaña", PrivateLibrary: "Biblioteca privada", ImportDatabase: "Importar base de datos", ExternalToolsRules: "Herramientas externas y reglas comunitarias", ImportCharacterRules: "Importar personaje o reglas", SwAdversaries: "Adversarios de SW", ImportAdversaries: "Importar adversarios", HelpRulesCoverage: "Ayuda y cobertura de reglas", OpenHelp: "Abrir ayuda", ShowAltitudeShadows: "Mostrar sombras de altitud", AltitudeShadows: "Sombras de altitud", AllowHomebrewIdentities: "Permitir identidades caseras" });
ui("fr", { SessionConsole: "Console de session", RollPool: "Lancer la réserve", UseLight: "Utiliser la Lumière", UseDark: "Utiliser l’Obscurité", SeedDestiny: "Initialiser la Destinée", DefaultSheetTheme: "Thème de fiche par défaut", FoundryInterfaceTheme: "Thème de l’interface Foundry", CompactDiceTray: "Barre de dés compacte près du chat", TransactionAuthority: "Autorité des transactions", UseThisGmTab: "Utiliser cet onglet MJ", GmSourceKey: "Clé des sources MJ", BackupRestoreKey: "Sauvegarder ou restaurer la clé", GmSourceLibrary: "Bibliothèque de sources MJ", SearchPrivateSources: "Rechercher des sources privées", CampaignRulesAdventure: "Règles de campagne et état de l’aventure", ChooseCampaignRules: "Choisir les règles de campagne", PrivateLibrary: "Bibliothèque privée", ImportDatabase: "Importer la base de données", ExternalToolsRules: "Outils externes et règles communautaires", ImportCharacterRules: "Importer un personnage ou des règles", SwAdversaries: "Adversaires SW", ImportAdversaries: "Importer des adversaires", HelpRulesCoverage: "Aide et couverture des règles", OpenHelp: "Ouvrir l’aide", ShowAltitudeShadows: "Afficher les ombres d’altitude", AltitudeShadows: "Ombres d’altitude", AllowHomebrewIdentities: "Autoriser les identités personnalisées" });
ui("de", { SessionConsole: "Sitzungskonsole", RollPool: "Pool würfeln", UseLight: "Licht verwenden", UseDark: "Dunkelheit verwenden", SeedDestiny: "Schicksal setzen", DefaultSheetTheme: "Standard-Bogenstil", FoundryInterfaceTheme: "Foundry-Oberflächenstil", CompactDiceTray: "Kompakte Würfelleiste beim Chat", TransactionAuthority: "Transaktionsautorität", UseThisGmTab: "Diesen SL-Tab verwenden", GmSourceKey: "SL-Quellschlüssel", BackupRestoreKey: "Schlüssel sichern oder wiederherstellen", GmSourceLibrary: "SL-Quellenbibliothek", SearchPrivateSources: "Private Quellen suchen", CampaignRulesAdventure: "Kampagnenregeln und Abenteuerstatus", ChooseCampaignRules: "Kampagnenregeln wählen", PrivateLibrary: "Private Bibliothek", ImportDatabase: "Datenbank importieren", ExternalToolsRules: "Externe Werkzeuge und Gemeinschaftsregeln", ImportCharacterRules: "Charakter oder Regeln importieren", SwAdversaries: "SW-Gegner", ImportAdversaries: "Gegner importieren", HelpRulesCoverage: "Hilfe und Regelabdeckung", OpenHelp: "Hilfe öffnen", ShowAltitudeShadows: "Höhenschatten anzeigen", AltitudeShadows: "Höhenschatten", AllowHomebrewIdentities: "Hausregel-Identitäten erlauben" });
ui("it", { SessionConsole: "Console di sessione", RollPool: "Tira il pool", UseLight: "Usa la luce", UseDark: "Usa l’oscurità", SeedDestiny: "Inizializza il Destino", DefaultSheetTheme: "Tema scheda predefinito", FoundryInterfaceTheme: "Tema interfaccia Foundry", CompactDiceTray: "Vassoio dadi compatto accanto alla chat", TransactionAuthority: "Autorità delle transazioni", UseThisGmTab: "Usa questa scheda del GM", GmSourceKey: "Chiave fonti GM", BackupRestoreKey: "Salva o ripristina chiave", GmSourceLibrary: "Libreria fonti GM", SearchPrivateSources: "Cerca fonti private", CampaignRulesAdventure: "Regole campagna e stato avventura", ChooseCampaignRules: "Scegli regole campagna", PrivateLibrary: "Libreria privata", ImportDatabase: "Importa database", ExternalToolsRules: "Strumenti esterni e regole della comunità", ImportCharacterRules: "Importa personaggio o regole", SwAdversaries: "Avversari SW", ImportAdversaries: "Importa avversari", HelpRulesCoverage: "Aiuto e copertura regole", OpenHelp: "Apri aiuto", ShowAltitudeShadows: "Mostra ombre d’altitudine", AltitudeShadows: "Ombre d’altitudine", AllowHomebrewIdentities: "Consenti identità personalizzate" });
ui("pt-BR", { SessionConsole: "Console da sessão", RollPool: "Rolar reserva", UseLight: "Usar luz", UseDark: "Usar trevas", SeedDestiny: "Definir Destino", DefaultSheetTheme: "Tema padrão da ficha", FoundryInterfaceTheme: "Tema da interface do Foundry", CompactDiceTray: "Bandeja compacta de dados junto ao chat", TransactionAuthority: "Autoridade de transações", UseThisGmTab: "Usar esta aba do GM", GmSourceKey: "Chave de fonte do GM", BackupRestoreKey: "Fazer backup ou restaurar chave", GmSourceLibrary: "Biblioteca de fontes do GM", SearchPrivateSources: "Pesquisar fontes privadas", CampaignRulesAdventure: "Regras da campanha e estado da aventura", ChooseCampaignRules: "Escolher regras da campanha", PrivateLibrary: "Biblioteca privada", ImportDatabase: "Importar banco de dados", ExternalToolsRules: "Ferramentas externas e regras da comunidade", ImportCharacterRules: "Importar personagem ou regras", SwAdversaries: "Adversários de SW", ImportAdversaries: "Importar adversários", HelpRulesCoverage: "Ajuda e cobertura de regras", OpenHelp: "Abrir ajuda", ShowAltitudeShadows: "Mostrar sombras de altitude", AltitudeShadows: "Sombras de altitude", AllowHomebrewIdentities: "Permitir identidades caseiras" });
ui("pt-PT", { SessionConsole: "Consola da sessão", RollPool: "Rolar reserva", UseLight: "Usar luz", UseDark: "Usar trevas", SeedDestiny: "Definir Destino", DefaultSheetTheme: "Tema predefinido da ficha", FoundryInterfaceTheme: "Tema da interface do Foundry", CompactDiceTray: "Bandeja compacta de dados junto ao chat", TransactionAuthority: "Autoridade de transações", UseThisGmTab: "Usar este separador do GM", GmSourceKey: "Chave de fontes do GM", BackupRestoreKey: "Guardar ou restaurar chave", GmSourceLibrary: "Biblioteca de fontes do GM", SearchPrivateSources: "Pesquisar fontes privadas", CampaignRulesAdventure: "Regras da campanha e estado da aventura", ChooseCampaignRules: "Escolher regras da campanha", PrivateLibrary: "Biblioteca privada", ImportDatabase: "Importar base de dados", ExternalToolsRules: "Ferramentas externas e regras da comunidade", ImportCharacterRules: "Importar personagem ou regras", SwAdversaries: "Adversários SW", ImportAdversaries: "Importar adversários", HelpRulesCoverage: "Ajuda e cobertura de regras", OpenHelp: "Abrir ajuda", ShowAltitudeShadows: "Mostrar sombras de altitude", AltitudeShadows: "Sombras de altitude", AllowHomebrewIdentities: "Permitir identidades caseiras" });
ui("ja", { SessionConsole: "セッションコンソール", RollPool: "プールを振る", UseLight: "ライトを使う", UseDark: "ダークを使う", SeedDestiny: "Destinyを設定", DefaultSheetTheme: "既定のシートテーマ", FoundryInterfaceTheme: "Foundryインターフェーステーマ", CompactDiceTray: "チャット横のコンパクトダイス", TransactionAuthority: "トランザクション権限", UseThisGmTab: "このGMタブを使う", GmSourceKey: "GMソースキー", BackupRestoreKey: "キーをバックアップ／復元", GmSourceLibrary: "GMソースライブラリ", SearchPrivateSources: "非公開ソースを検索", CampaignRulesAdventure: "キャンペーンルールと冒険状態", ChooseCampaignRules: "キャンペーンルールを選択", PrivateLibrary: "プライベートライブラリ", ImportDatabase: "データベースをインポート", ExternalToolsRules: "外部ツールとコミュニティルール", ImportCharacterRules: "キャラクターまたはルールをインポート", SwAdversaries: "SWアドバーサリー", ImportAdversaries: "敵をインポート", HelpRulesCoverage: "ヘルプとルール対応", OpenHelp: "ヘルプを開く", ShowAltitudeShadows: "高度の影を表示", AltitudeShadows: "高度の影", AllowHomebrewIdentities: "ホームブリュー種別を許可" });
ui("ko", { SessionConsole: "세션 콘솔", RollPool: "풀 굴리기", UseLight: "빛 사용", UseDark: "어둠 사용", SeedDestiny: "Destiny 설정", DefaultSheetTheme: "기본 시트 테마", FoundryInterfaceTheme: "Foundry 인터페이스 테마", CompactDiceTray: "채팅 옆 간단 주사위 트레이", TransactionAuthority: "거래 권한", UseThisGmTab: "이 GM 탭 사용", GmSourceKey: "GM 출처 키", BackupRestoreKey: "키 백업 또는 복원", GmSourceLibrary: "GM 출처 라이브러리", SearchPrivateSources: "비공개 출처 검색", CampaignRulesAdventure: "캠페인 규칙 및 모험 상태", ChooseCampaignRules: "캠페인 규칙 선택", PrivateLibrary: "비공개 라이브러리", ImportDatabase: "데이터베이스 가져오기", ExternalToolsRules: "외부 도구 및 커뮤니티 규칙", ImportCharacterRules: "캐릭터 또는 규칙 가져오기", SwAdversaries: "SW 적", ImportAdversaries: "적 가져오기", HelpRulesCoverage: "도움말 및 규칙 적용 범위", OpenHelp: "도움말 열기", ShowAltitudeShadows: "고도 그림자 표시", AltitudeShadows: "고도 그림자", AllowHomebrewIdentities: "홈브루 정체성 허용" });
ui("zh-CN", { SessionConsole: "会话控制台", RollPool: "投掷骰池", UseLight: "使用光明", UseDark: "使用黑暗", SeedDestiny: "设置命运", DefaultSheetTheme: "默认角色卡主题", FoundryInterfaceTheme: "Foundry 界面主题", CompactDiceTray: "聊天旁的紧凑骰盘", TransactionAuthority: "事务权限", UseThisGmTab: "使用此 GM 标签页", GmSourceKey: "GM 来源密钥", BackupRestoreKey: "备份或恢复密钥", GmSourceLibrary: "GM 来源库", SearchPrivateSources: "搜索私有来源", CampaignRulesAdventure: "战役规则与冒险状态", ChooseCampaignRules: "选择战役规则", PrivateLibrary: "私有库", ImportDatabase: "导入数据库", ExternalToolsRules: "外部工具与社区规则", ImportCharacterRules: "导入角色或规则", SwAdversaries: "SW 敌人", ImportAdversaries: "导入敌人", HelpRulesCoverage: "帮助与规则覆盖", OpenHelp: "打开帮助", ShowAltitudeShadows: "显示高度阴影", AltitudeShadows: "高度阴影", AllowHomebrewIdentities: "允许自定义身份" });
ui("zh-TW", { SessionConsole: "工作階段主控台", RollPool: "擲骰池", UseLight: "使用光明", UseDark: "使用黑暗", SeedDestiny: "設定命運", DefaultSheetTheme: "預設角色卡主題", FoundryInterfaceTheme: "Foundry 介面主題", CompactDiceTray: "聊天旁的精簡骰盤", TransactionAuthority: "交易權限", UseThisGmTab: "使用此 GM 分頁", GmSourceKey: "GM 來源金鑰", BackupRestoreKey: "備份或還原金鑰", GmSourceLibrary: "GM 來源庫", SearchPrivateSources: "搜尋私人來源", CampaignRulesAdventure: "戰役規則與冒險狀態", ChooseCampaignRules: "選擇戰役規則", PrivateLibrary: "私人資料庫", ImportDatabase: "匯入資料庫", ExternalToolsRules: "外部工具與社群規則", ImportCharacterRules: "匯入角色或規則", SwAdversaries: "SW 敵人", ImportAdversaries: "匯入敵人", HelpRulesCoverage: "說明與規則涵蓋", OpenHelp: "開啟說明", ShowAltitudeShadows: "顯示高度陰影", AltitudeShadows: "高度陰影", AllowHomebrewIdentities: "允許自訂身分" });
ui("pl", { SessionConsole: "Konsola sesji", RollPool: "Rzuć pulę", UseLight: "Użyj światła", UseDark: "Użyj ciemności", SeedDestiny: "Ustaw Przeznaczenie", DefaultSheetTheme: "Domyślny motyw karty", FoundryInterfaceTheme: "Motyw interfejsu Foundry", CompactDiceTray: "Kompaktowa taca kości przy czacie", TransactionAuthority: "Autorytet transakcji", UseThisGmTab: "Użyj tej karty MG", GmSourceKey: "Klucz źródeł MG", BackupRestoreKey: "Kopia lub przywrócenie klucza", GmSourceLibrary: "Biblioteka źródeł MG", SearchPrivateSources: "Szukaj źródeł prywatnych", CampaignRulesAdventure: "Zasady kampanii i stan przygody", ChooseCampaignRules: "Wybierz zasady kampanii", PrivateLibrary: "Biblioteka prywatna", ImportDatabase: "Importuj bazę danych", ExternalToolsRules: "Narzędzia zewnętrzne i zasady społeczności", ImportCharacterRules: "Importuj postać lub zasady", SwAdversaries: "Wrogowie SW", ImportAdversaries: "Importuj wrogów", HelpRulesCoverage: "Pomoc i zakres zasad", OpenHelp: "Otwórz pomoc", ShowAltitudeShadows: "Pokaż cienie wysokości", AltitudeShadows: "Cienie wysokości", AllowHomebrewIdentities: "Zezwalaj na własne tożsamości" });
ui("ru", { SessionConsole: "Консоль сессии", RollPool: "Бросить пул", UseLight: "Использовать Свет", UseDark: "Использовать Тьму", SeedDestiny: "Задать Судьбу", DefaultSheetTheme: "Тема листа по умолчанию", FoundryInterfaceTheme: "Тема интерфейса Foundry", CompactDiceTray: "Компактная панель костей у чата", TransactionAuthority: "Полномочия транзакций", UseThisGmTab: "Использовать эту вкладку ведущего", GmSourceKey: "Ключ источников ведущего", BackupRestoreKey: "Создать или восстановить ключ", GmSourceLibrary: "Библиотека источников ведущего", SearchPrivateSources: "Поиск частных источников", CampaignRulesAdventure: "Правила кампании и состояние приключения", ChooseCampaignRules: "Выбрать правила кампании", PrivateLibrary: "Частная библиотека", ImportDatabase: "Импортировать базу данных", ExternalToolsRules: "Внешние инструменты и правила сообщества", ImportCharacterRules: "Импортировать персонажа или правила", SwAdversaries: "Противники SW", ImportAdversaries: "Импортировать противников", HelpRulesCoverage: "Помощь и покрытие правил", OpenHelp: "Открыть помощь", ShowAltitudeShadows: "Показывать тени высоты", AltitudeShadows: "Тени высоты", AllowHomebrewIdentities: "Разрешить хоумбрю-идентичности" });
ui("nl", { SessionConsole: "Sessieconsole", RollPool: "Pool werpen", UseLight: "Licht gebruiken", UseDark: "Donker gebruiken", SeedDestiny: "Lot instellen", DefaultSheetTheme: "Standaard bladthema", FoundryInterfaceTheme: "Foundry-interfacethema", CompactDiceTray: "Compacte dobbelbak naast chat", TransactionAuthority: "Transactiebevoegdheid", UseThisGmTab: "Dit GM-tabblad gebruiken", GmSourceKey: "GM-bronsleutel", BackupRestoreKey: "Sleutel back-uppen of herstellen", GmSourceLibrary: "GM-bronnenbibliotheek", SearchPrivateSources: "Privébronnen zoeken", CampaignRulesAdventure: "Campagneregels en avonturenstatus", ChooseCampaignRules: "Campagneregels kiezen", PrivateLibrary: "Privébibliotheek", ImportDatabase: "Database importeren", ExternalToolsRules: "Externe hulpmiddelen en gemeenschapsregels", ImportCharacterRules: "Personage of regels importeren", SwAdversaries: "SW-tegenstanders", ImportAdversaries: "Tegenstanders importeren", HelpRulesCoverage: "Hulp en regeldekking", OpenHelp: "Hulp openen", ShowAltitudeShadows: "Hoogteschaduwen tonen", AltitudeShadows: "Hoogteschaduwen", AllowHomebrewIdentities: "Homebrew-identiteiten toestaan" });
ui("sv", { SessionConsole: "Sessionskonsol", RollPool: "Slå pool", UseLight: "Använd ljus", UseDark: "Använd mörker", SeedDestiny: "Ställ in öde", DefaultSheetTheme: "Standardtema för blad", FoundryInterfaceTheme: "Foundry-gränssnittstema", CompactDiceTray: "Kompakt tärningsbricka vid chatten", TransactionAuthority: "Transaktionsbehörighet", UseThisGmTab: "Använd denna spelledarflik", GmSourceKey: "Spelledarens källnyckel", BackupRestoreKey: "Säkerhetskopiera eller återställ nyckel", GmSourceLibrary: "Spelledarens källbibliotek", SearchPrivateSources: "Sök privata källor", CampaignRulesAdventure: "Kampanjregler och äventyrstillstånd", ChooseCampaignRules: "Välj kampanjregler", PrivateLibrary: "Privat bibliotek", ImportDatabase: "Importera databas", ExternalToolsRules: "Externa verktyg och gemenskapsregler", ImportCharacterRules: "Importera rollperson eller regler", SwAdversaries: "SW-motståndare", ImportAdversaries: "Importera motståndare", HelpRulesCoverage: "Hjälp och regeltäckning", OpenHelp: "Öppna hjälp", ShowAltitudeShadows: "Visa höjdskuggor", AltitudeShadows: "Höjdskuggor", AllowHomebrewIdentities: "Tillåt egna identiteter" });

for (const [locale, overrides] of Object.entries(locales)) {
  const data = { ...base, ...overrides };
  await writeFile(`lang/${locale}.json`, `${JSON.stringify(data, null, 2)}\n`, "utf8");
}
await writeFile("lang/en.json", `${JSON.stringify(base, null, 2)}\n`, "utf8");
