import { SYSTEM_ID } from "./config.mjs";
import { validateTree } from "./advancement.mjs";
import {
  refreshGMNotes,
  preparePrivateNotes,
  GM_NOTES_PACK,
} from "./gm-notes.mjs";
export function refreshLibraryLabels() {
  // Keep persisted compendium IDs compatible with the initial release.
  for (const pack of game.packs)
    if (
      /^world\.starfall-(?:item|actor|journalentry|gm-notes)$/.test(
        pack.collection,
      ) &&
      pack.metadata.label.startsWith("Starfall · ")
    )
      pack.metadata.label = pack.metadata.label.replace(
        "Starfall · ",
        "Star Wars FFG · ",
      );
}
export function validateBundle(bundle) {
  if (bundle?.format !== "starfall-library" || bundle.version !== 1)
    throw new Error(
      "Choose a Star Wars FFG library JSON generated by the local importer.",
    );
  let total = 0;
  for (const [type, documents] of Object.entries(bundle.documents ?? {})) {
    if (
      !["Actor", "Item", "JournalEntry"].includes(type) ||
      !Array.isArray(documents)
    )
      throw new Error("Unsupported library document type.");
    const ids = new Set();
    for (const doc of documents) {
      if (!/^[a-zA-Z0-9]{16}$/.test(doc._id) || ids.has(doc._id) || !doc.name)
        throw new Error(
          "Library documents require unique valid IDs and names.",
        );
      ids.add(doc._id);
      if (doc.type === "specialization" && doc.system?.tree?.nodes?.length)
        validateTree(doc.system.tree);
    }
    total += documents.length;
  }
  if (!total || total > 20000)
    throw new Error("Library must contain between 1 and 20,000 entries.");
  return bundle;
}
export async function importLibrary(bundle, onProgress = () => {}) {
  if (!game.user.isGM) throw new Error("Only the GM can import a library.");
  validateBundle(bundle);
  const privateSources = (bundle.documents.JournalEntry ?? []).filter(
    (doc) => doc.flags?.[SYSTEM_ID]?.gmOnly,
  );
  let sealedSources = [];
  if (privateSources.length) {
    await refreshGMNotes();
    sealedSources = await preparePrivateNotes(
      privateSources,
      game.packs.get(GM_NOTES_PACK),
    );
  }
  const report = {};
  const batches = [];
  for (const [type, documents] of Object.entries(bundle.documents)) {
    if (type === "JournalEntry") {
      batches.push([
        type,
        documents.filter((doc) => !doc.flags?.[SYSTEM_ID]?.gmOnly),
        false,
      ]);
      batches.push([type, sealedSources, true]);
    } else batches.push([type, documents, false]);
  }
  for (const [type, documents, privateNotes] of batches) {
    if (!documents.length) continue;
    const name = privateNotes
      ? "starfall-gm-notes"
      : `starfall-${type.toLowerCase()}`;
    let pack = game.packs.get(`world.${name}`);
    if (!pack)
      pack =
        await foundry.documents.collections.CompendiumCollection.createCompendium(
          {
            name,
            label: `Star Wars FFG · ${privateNotes ? "Private GM source notes" : type === "Actor" ? "Actors & vehicles" : type === "Item" ? "Equipment & advancement" : "Places & references"}`,
            type,
            ...(privateNotes
              ? {
                  ownership: {
                    GAMEMASTER: "OWNER",
                    ASSISTANT: "OWNER",
                    TRUSTED: "NONE",
                    PLAYER: "NONE",
                  },
                }
              : {}),
          },
        );
    if (pack.documentName !== type)
      throw new Error(`Unexpected document type for ${name}`);
    const locked = pack.locked;
    await pack.configure({
      locked: false,
      ...(privateNotes
        ? {
            ownership: {
              GAMEMASTER: "OWNER",
              ASSISTANT: "OWNER",
              TRUSTED: "NONE",
              PLAYER: "NONE",
            },
          }
        : {}),
    });
    try {
      await pack.getIndex({
        fields:
          type === "Actor"
            ? [
                `flags.${SYSTEM_ID}.swa.notesId`,
                `flags.${SYSTEM_ID}.swa.omittedProse`,
              ]
            : [],
      });
      const missing = documents.filter((doc) => !pack.index.has(doc._id));
      const createdIds = new Set(missing.map((doc) => doc._id));
      for (let i = 0; i < missing.length; i += 100) {
        await pack.documentClass.createDocuments(missing.slice(i, i + 100), {
          pack: pack.collection,
          keepId: true,
          render: false,
        });
        onProgress(type, Math.min(i + 100, missing.length), missing.length);
      }
      if (type === "Actor") {
        const links = documents
          .filter(
            (doc) =>
              !createdIds.has(doc._id) &&
              doc.flags?.[SYSTEM_ID]?.swa?.notesId &&
              (pack.index.get(doc._id)?.flags?.[SYSTEM_ID]?.swa?.notesId !==
                doc.flags[SYSTEM_ID].swa.notesId ||
                pack.index.get(doc._id)?.flags?.[SYSTEM_ID]?.swa
                  ?.omittedProse !== false),
          )
          .map((doc) => ({
            _id: doc._id,
            [`flags.${SYSTEM_ID}.swa.notesId`]:
              doc.flags[SYSTEM_ID].swa.notesId,
            [`flags.${SYSTEM_ID}.swa.omittedProse`]: false,
          }));
        for (let i = 0; i < links.length; i += 100)
          await pack.documentClass.updateDocuments(links.slice(i, i + 100), {
            pack: pack.collection,
            render: false,
          });
      }
      report[privateNotes ? "GMNotes" : type] = {
        created: missing.length,
        preserved: documents.length - missing.length,
      };
    } finally {
      await pack.configure({ locked });
    }
  }
  if (report.GMNotes) await refreshGMNotes();
  return report;
}
export async function importWithProgress(bundle) {
  const progress = ui.notifications.info("Preparing reference import…", {
    progress: true,
  });
  try {
    const report = await importLibrary(bundle, (type, done, total) =>
      progress.update({
        message: `Importing ${type}: ${done} / ${total}`,
        pct: Math.min(0.95, done / total),
      }),
    );
    progress.update({ pct: 1, message: "Reference import complete." });
    return report;
  } catch (error) {
    progress.remove();
    throw error;
  }
}
