import { SYSTEM_ID } from "./config.mjs";
import { validateTree } from "./advancement.mjs";
import { refreshGMNotes, preparePrivateNotes } from "./gm-notes.mjs";
import {
  getLibraryPack,
  libraryPackName,
  libraryPackLabel,
} from "./library-packs.mjs";
export { refreshLibraryLabels } from "./library-packs.mjs";
export function mergeSpecializationEnrichment(existing, incoming) {
  if (
    !["specialization", "signatureAbility"].includes(existing?.type) ||
    incoming?.type !== existing?.type ||
    !incoming.system?.tree?.nodes?.length
  )
    return null;
  const current = existing.system?.tree;
  if (!current?.nodes?.length) return structuredClone(incoming.system.tree);
  const incomingNodes = new Map(
      incoming.system.tree.nodes.map((node) => [node.id, node]),
    ),
    nodes = current.nodes.map((node) => {
      const source = incomingNodes.get(node.id);
      if (!source) return node;
      return {
        ...node,
        ...(!node.key && source.key ? { key: source.key } : {}),
        ...(!node.activation && source.activation
          ? { activation: source.activation }
          : {}),
        ...(!node.summary && source.summary ? { summary: source.summary } : {}),
        ...(!(node.effects?.length) && source.effects?.length
          ? { effects: structuredClone(source.effects) }
          : {}),
        ...(!node.reference && source.reference
          ? { reference: structuredClone(source.reference) }
          : {}),
      };
    }),
    merged = {
      ...current,
      nodes,
      ...(!current.verified && incoming.system.tree.verified
        ? { verified: true }
        : {}),
      ...(!current.verification && incoming.system.tree.verification
        ? { verification: structuredClone(incoming.system.tree.verification) }
        : {}),
    };
  return JSON.stringify(merged) === JSON.stringify(current) ? null : merged;
}
export function validateBundle(bundle) {
  // Version-one libraries keep the same schema across branding changes.
  if (
    !/^[a-z0-9]+(?:-[a-z0-9]+)*-library$/.test(bundle?.format ?? "") ||
    bundle.version !== 1
  )
    throw new Error(
      "Choose a Star Wars FFG library JSON generated by the local importer.",
    );
  let total = 0;
  for (const [type, documents] of Object.entries(bundle.documents ?? {})) {
    if (
      !["Actor", "Item", "JournalEntry"].includes(type) ||
      !Array.isArray(documents)
    )
      throw new Error("Unsupported library document type.");
    const ids = new Set();
    for (const doc of documents) {
      if (!/^[a-zA-Z0-9]{16}$/.test(doc._id) || ids.has(doc._id) || !doc.name)
        throw new Error(
          "Library documents require unique valid IDs and names.",
        );
      ids.add(doc._id);
      if (
        ["specialization", "signatureAbility"].includes(doc.type) &&
        doc.system?.tree?.nodes?.length
      )
        validateTree(doc.system.tree);
    }
    total += documents.length;
  }
  if (!total || total > 20000)
    throw new Error("Library must contain between 1 and 20,000 entries.");
  return bundle;
}
export async function importLibrary(bundle, onProgress = () => {}) {
  if (!game.user.isGM) throw new Error("Only the GM can import a library.");
  validateBundle(bundle);
  const privateSources = (bundle.documents.JournalEntry ?? []).filter(
    (doc) => doc.flags?.[SYSTEM_ID]?.gmOnly,
  );
  let sealedSources = [];
  if (privateSources.length) {
    await refreshGMNotes();
    sealedSources = await preparePrivateNotes(
      privateSources,
      getLibraryPack("GMNotes"),
    );
  }
  const report = {};
  const batches = [];
  for (const [type, documents] of Object.entries(bundle.documents)) {
    if (type === "JournalEntry") {
      batches.push([
        type,
        documents.filter((doc) => !doc.flags?.[SYSTEM_ID]?.gmOnly),
        false,
      ]);
      batches.push([type, sealedSources, true]);
    } else batches.push([type, documents, false]);
  }
  for (const [type, documents, privateNotes] of batches) {
    if (!documents.length) continue;
    const kind = privateNotes ? "GMNotes" : type;
    const name = libraryPackName(kind);
    let pack = getLibraryPack(kind);
    if (!pack)
      pack =
        await foundry.documents.collections.CompendiumCollection.createCompendium(
          {
            name,
            label: libraryPackLabel(kind),
            type,
            ...(privateNotes
              ? {
                  ownership: {
                    GAMEMASTER: "OWNER",
                    ASSISTANT: "OWNER",
                    TRUSTED: "NONE",
                    PLAYER: "NONE",
                  },
                }
              : {}),
          },
        );
    if (pack.documentName !== type)
      throw new Error(`Unexpected document type for ${name}`);
    const locked = pack.locked;
    await pack.configure({
      locked: false,
      ...(privateNotes
        ? {
            ownership: {
              GAMEMASTER: "OWNER",
              ASSISTANT: "OWNER",
              TRUSTED: "NONE",
              PLAYER: "NONE",
            },
          }
        : {}),
    });
    try {
      await pack.getIndex({
        fields:
          type === "Actor"
            ? [
                `flags.${SYSTEM_ID}.swa.notesId`,
                `flags.${SYSTEM_ID}.swa.omittedProse`,
              ]
            : [],
      });
      const missing = documents.filter((doc) => !pack.index.has(doc._id));
      const createdIds = new Set(missing.map((doc) => doc._id));
      for (let i = 0; i < missing.length; i += 100) {
        await pack.documentClass.createDocuments(missing.slice(i, i + 100), {
          pack: pack.collection,
          keepId: true,
          render: false,
        });
        onProgress(type, Math.min(i + 100, missing.length), missing.length);
      }
      let enriched = 0;
      if (type === "Item") {
        const updates = [];
        for (const incoming of documents.filter(
          (doc) =>
            ["specialization", "signatureAbility"].includes(doc.type) &&
            !createdIds.has(doc._id),
        )) {
          const existing = await pack.getDocument(incoming._id),
            existingObject = existing?.toObject?.() ?? existing;
          const tree = mergeSpecializationEnrichment(existingObject, incoming);
          if (tree) {
            const update = { _id: incoming._id, "system.tree": tree };
            if (incoming.type === "signatureAbility") {
              if (
                !existing.system?.eligibleCareers?.length &&
                incoming.system?.eligibleCareers?.length
              )
                update["system.eligibleCareers"] =
                  incoming.system.eligibleCareers;
              if (
                !existing.system?.matchingNodes?.length &&
                incoming.system?.matchingNodes?.length
              )
                update["system.matchingNodes"] = incoming.system.matchingNodes;
              if (
                !existing.system?.abilityCategory &&
                incoming.system?.abilityCategory
              )
                update["system.abilityCategory"] =
                  incoming.system.abilityCategory;
              if (
                existing.system?.incomplete?.includes("tree") &&
                incoming.system?.incomplete
              )
                update["system.incomplete"] = incoming.system.incomplete;
            }
            updates.push(update);
          }
        }
        for (let i = 0; i < updates.length; i += 100)
          await pack.documentClass.updateDocuments(updates.slice(i, i + 100), {
            pack: pack.collection,
            render: false,
          });
        enriched = updates.length;
      }
      if (type === "Actor") {
        const links = documents
          .filter(
            (doc) =>
              !createdIds.has(doc._id) &&
              doc.flags?.[SYSTEM_ID]?.swa?.notesId &&
              (pack.index.get(doc._id)?.flags?.[SYSTEM_ID]?.swa?.notesId !==
                doc.flags[SYSTEM_ID].swa.notesId ||
                pack.index.get(doc._id)?.flags?.[SYSTEM_ID]?.swa
                  ?.omittedProse !== false),
          )
          .map((doc) => ({
            _id: doc._id,
            [`flags.${SYSTEM_ID}.swa.notesId`]:
              doc.flags[SYSTEM_ID].swa.notesId,
            [`flags.${SYSTEM_ID}.swa.omittedProse`]: false,
          }));
        for (let i = 0; i < links.length; i += 100)
          await pack.documentClass.updateDocuments(links.slice(i, i + 100), {
            pack: pack.collection,
            render: false,
          });
      }
      report[privateNotes ? "GMNotes" : type] = {
        created: missing.length,
        preserved: documents.length - missing.length,
        ...(enriched ? { enriched } : {}),
      };
    } finally {
      await pack.configure({ locked });
    }
  }
  if (report.GMNotes) await refreshGMNotes();
  return report;
}
export async function importWithProgress(bundle) {
  const progress = ui.notifications.info("Preparing reference import…", {
    progress: true,
  });
  try {
    const report = await importLibrary(bundle, (type, done, total) =>
      progress.update({
        message: `Importing ${type}: ${done} / ${total}`,
        pct: Math.min(0.95, done / total),
      }),
    );
    progress.update({ pct: 1, message: "Reference import complete." });
    return report;
  } catch (error) {
    progress.remove();
    throw error;
  }
}
