import { SYSTEM_ID } from "./config.mjs";
import { validateTree } from "./advancement.mjs";
export function validateBundle(bundle) {
  if (bundle?.format !== "starfall-library" || bundle.version !== 1)
    throw new Error(
      "Choose a Starfall library JSON generated by the local importer.",
    );
  let total = 0;
  for (const [type, documents] of Object.entries(bundle.documents ?? {})) {
    if (
      !["Actor", "Item", "JournalEntry"].includes(type) ||
      !Array.isArray(documents)
    )
      throw new Error("Unsupported library document type.");
    const ids = new Set();
    for (const doc of documents) {
      if (!/^[a-zA-Z0-9]{16}$/.test(doc._id) || ids.has(doc._id) || !doc.name)
        throw new Error(
          "Library documents require unique valid IDs and names.",
        );
      ids.add(doc._id);
      if (doc.type === "specialization" && doc.system?.tree?.nodes?.length)
        validateTree(doc.system.tree);
    }
    total += documents.length;
  }
  if (!total || total > 20000)
    throw new Error("Library must contain between 1 and 20,000 entries.");
  return bundle;
}
export async function importLibrary(bundle, onProgress = () => {}) {
  if (!game.user.isGM) throw new Error("Only the GM can import a library.");
  validateBundle(bundle);
  const report = {};
  for (const [type, documents] of Object.entries(bundle.documents)) {
    const name = `starfall-${type.toLowerCase()}`;
    let pack = game.packs.get(`world.${name}`);
    if (!pack)
      pack =
        await foundry.documents.collections.CompendiumCollection.createCompendium(
          {
            name,
            label: `Starfall · ${type === "Actor" ? "Vehicles" : type === "Item" ? "Equipment & advancement" : "Places & references"}`,
            type,
          },
        );
    if (pack.documentName !== type)
      throw new Error(`Unexpected document type for ${name}`);
    const locked = pack.locked;
    await pack.configure({ locked: false });
    try {
      await pack.getIndex();
      const missing = documents.filter((doc) => !pack.index.has(doc._id));
      for (let i = 0; i < missing.length; i += 100) {
        await pack.documentClass.createDocuments(missing.slice(i, i + 100), {
          pack: pack.collection,
          keepId: true,
        });
        onProgress(type, Math.min(i + 100, missing.length), missing.length);
      }
      report[type] = {
        created: missing.length,
        preserved: documents.length - missing.length,
      };
    } finally {
      await pack.configure({ locked });
    }
  }
  return report;
}
